"""Điểm ngữ pháp C42 (A1 + A2) — nguồn seed cho `seed_grammar`.

Mỗi mục: level, order, category, title, subtitle, form, formula + parts, note (mẹo vàng), explanation,
mistake (hint, wrong, right), conjugation, examples [(en, vi)], exercises [(prompt_en, prompt_vi, options,
answer_index, explanation)].
"""

# fmt: off
POINTS = [
    dict(level="A1", order=1, category="Thì", title_vi="Động từ to be (am/is/are)", title_en="Verb to be",
         subtitle_vi="Khái niệm cốt lõi · 3 quy tắc", form_vi="Thể khẳng định · Hiện tại đơn",
         formula="S + be + N/Adj",
         parts=[("S", "Chủ ngữ"), ("be", "am / is / are"), ("N / Adj", "Danh / Tính từ")],
         note_vi="Nắm chắc bản chất cấu trúc to be trước khi học các thì tiếp diễn nhé!",
         explanation_vi='Động từ "to be" diễn tả trạng thái, tính chất hoặc danh tính của chủ ngữ tại thời điểm hiện tại. Chia theo chủ ngữ: I → am, He/She/It → is, You/We/They → are.',
         mistake=("Thường bỏ quên am/is/are khi đi với tính từ.", "She very beautiful", "She is very beautiful"),
         conjugation=[("I", "am"), ("He / She / It (Số ít)", "is"), ("You / We / They (Số nhiều)", "are")],
         examples=[("I am a student.", "Tôi là một học sinh."), ("She is happy today.", "Hôm nay cô ấy rất vui."), ("They are from Vietnam.", "Họ đến từ Việt Nam.")],
         exercises=[
             ("I ___ a teacher.", "Tôi là giáo viên.", ["am", "is", "are"], 0, "Chủ ngữ I luôn đi với am."),
             ("She ___ my sister.", "Cô ấy là chị tôi.", ["am", "is", "are"], 1, "She là ngôi thứ ba số ít → is."),
             ("They ___ at home.", "Họ đang ở nhà.", ["am", "is", "are"], 2, "They số nhiều → are."),
             ("We ___ students.", "Chúng tôi là học sinh.", ["is", "are", "am"], 1, "We → are."),
             ("It ___ cold today.", "Hôm nay trời lạnh.", ["is", "are", "am"], 0, "It → is."),
             ("You ___ very kind.", "Bạn rất tốt bụng.", ["is", "am", "are"], 2, "You luôn đi với are."),
             ("My parents ___ doctors.", "Bố mẹ tôi là bác sĩ.", ["is", "are", "am"], 1, "My parents = they → are."),
             ("He ___ not here.", "Anh ấy không có ở đây.", ["am", "are", "is"], 2, "He → is; phủ định thêm not."),
         ]),
    dict(level="A1", order=2, category="Mạo từ", title_vi="Mạo từ a/an/the", title_en="Articles a/an/the",
         subtitle_vi="Quy tắc danh từ đếm được", form_vi="Mạo từ · Danh từ số ít",
         formula="a/an + N (số ít)",
         parts=[("a", "Trước phụ âm"), ("an", "Trước nguyên âm"), ("the", "Đã xác định")],
         note_vi="Nghe âm đầu, không nhìn chữ cái: an hour (âm /aʊ/), a university (âm /j/).",
         explanation_vi="a/an dùng cho danh từ đếm được số ít chưa xác định: a trước âm phụ âm, an trước âm nguyên âm. the dùng khi cả người nói và người nghe đều biết đang nhắc đến cái nào.",
         mistake=("Chọn a/an theo chữ cái thay vì theo âm.", "a apple, an university", "an apple, a university"),
         conjugation=[("Âm phụ âm", "a book, a cat"), ("Âm nguyên âm", "an egg, an hour"), ("Đã xác định", "the sun, the book you gave me")],
         examples=[("I have a dog.", "Tôi có một con chó."), ("She eats an apple every day.", "Cô ấy ăn một quả táo mỗi ngày."), ("The moon is bright tonight.", "Tối nay trăng sáng.")],
         exercises=[
             ("I need ___ umbrella.", "Tôi cần một cái ô.", ["a", "an", "the"], 1, "umbrella bắt đầu bằng âm nguyên âm → an."),
             ("She is ___ nurse.", "Cô ấy là y tá.", ["a", "an", "the"], 0, "nurse âm phụ âm → a."),
             ("___ sun rises in the east.", "Mặt trời mọc ở đằng đông.", ["A", "An", "The"], 2, "Vật duy nhất → the."),
             ("He waited for ___ hour.", "Anh ấy đợi một tiếng.", ["a", "an", "the"], 1, "hour đọc /aʊə/ → an."),
             ("This is ___ university.", "Đây là một trường đại học.", ["a", "an", "the"], 0, "university đọc /juː/ → a."),
             ("Close ___ door, please.", "Làm ơn đóng cửa lại.", ["a", "an", "the"], 2, "Cả hai đều biết cửa nào → the."),
             ("I bought ___ orange.", "Tôi mua một quả cam.", ["a", "an", "the"], 1, "orange âm nguyên âm → an."),
             ("We have ___ big house.", "Chúng tôi có một ngôi nhà lớn.", ["a", "an", "the"], 0, "big âm phụ âm → a."),
         ]),
    dict(level="A1", order=3, category="Thì", title_vi="Thì hiện tại đơn", title_en="Present simple",
         subtitle_vi="Diễn tả thói quen & sự thật", form_vi="Thể khẳng định · Hiện tại đơn",
         formula="S + V(s/es) + O",
         parts=[("S", "Chủ ngữ"), ("V(s/es)", "Động từ chia"), ("O", "Tân ngữ")],
         note_vi="He/She/It thì động từ thêm s/es — quên s là lỗi phổ biến nhất của người Việt!",
         explanation_vi="Thì hiện tại đơn diễn tả thói quen, lịch trình và sự thật hiển nhiên. Với He/She/It, động từ thêm -s (hoặc -es sau o, s, sh, ch, x). Phủ định dùng do not / does not + V nguyên mẫu.",
         mistake=("Quên thêm -s với ngôi thứ ba số ít.", "She go to school every day", "She goes to school every day"),
         conjugation=[("I / You / We / They", "work, go, watch"), ("He / She / It", "works, goes, watches"), ("Phủ định", "don't / doesn't + V")],
         examples=[("I drink coffee every morning.", "Tôi uống cà phê mỗi sáng."), ("He works in a bank.", "Anh ấy làm việc ở ngân hàng."), ("The sun rises in the east.", "Mặt trời mọc ở đằng đông.")],
         exercises=[
             ("She ___ English every day.", "Cô ấy học tiếng Anh mỗi ngày.", ["study", "studies", "studying"], 1, "She → studies (y → ies)."),
             ("They ___ football on Sundays.", "Họ chơi bóng vào Chủ nhật.", ["play", "plays", "playing"], 0, "They → V nguyên mẫu."),
             ("He ___ TV at night.", "Anh ấy xem TV buổi tối.", ["watch", "watchs", "watches"], 2, "watch + es."),
             ("I ___ like spicy food.", "Tôi không thích đồ cay.", ["don't", "doesn't", "am not"], 0, "I → don't."),
             ("My mother ___ breakfast at 6.", "Mẹ tôi nấu bữa sáng lúc 6 giờ.", ["cook", "cooks", "cooking"], 1, "My mother = she → cooks."),
             ("Water ___ at 100°C.", "Nước sôi ở 100°C.", ["boil", "boils", "boiling"], 1, "Sự thật hiển nhiên, it → boils."),
             ("She ___ eat meat.", "Cô ấy không ăn thịt.", ["don't", "doesn't", "isn't"], 1, "She → doesn't + V nguyên mẫu."),
             ("We ___ to school by bus.", "Chúng tôi đi học bằng xe buýt.", ["go", "goes", "going"], 0, "We → go."),
         ]),
    dict(level="A1", order=4, category="Đại từ", title_vi="Đại từ nhân xưng", title_en="Personal pronouns",
         subtitle_vi="Chủ ngữ & Tân ngữ thông dụng", form_vi="Đại từ · Chủ ngữ / Tân ngữ",
         formula="S (I/you/he…) + V + O (me/you/him…)",
         parts=[("I / he / she", "Chủ ngữ"), ("V", "Động từ"), ("me / him / her", "Tân ngữ")],
         note_vi="Đứng trước động từ dùng dạng chủ ngữ, đứng sau động từ / giới từ dùng dạng tân ngữ.",
         explanation_vi="Đại từ chủ ngữ (I, you, he, she, it, we, they) thay cho người/vật làm chủ hành động. Đại từ tân ngữ (me, you, him, her, it, us, them) đứng sau động từ hoặc giới từ.",
         mistake=("Dùng dạng chủ ngữ ở vị trí tân ngữ.", "She loves he", "She loves him"),
         conjugation=[("I → me", "Tôi"), ("He → him / She → her", "Anh ấy / Cô ấy"), ("We → us / They → them", "Chúng tôi / Họ")],
         examples=[("I love her.", "Tôi yêu cô ấy."), ("Give it to me.", "Đưa nó cho tôi."), ("They invited us to dinner.", "Họ mời chúng tôi ăn tối.")],
         exercises=[
             ("Can you help ___?", "Bạn giúp tôi được không?", ["I", "me", "my"], 1, "Sau động từ → me."),
             ("___ is my best friend.", "Cô ấy là bạn thân nhất của tôi.", ["She", "Her", "Hers"], 0, "Đứng đầu câu làm chủ ngữ → She."),
             ("I saw ___ at the park.", "Tôi thấy họ ở công viên.", ["they", "them", "their"], 1, "Sau saw → them."),
             ("___ are going to the beach.", "Chúng tôi sẽ đi biển.", ["We", "Us", "Our"], 0, "Chủ ngữ → We."),
             ("This gift is for ___.", "Món quà này dành cho anh ấy.", ["he", "him", "his"], 1, "Sau giới từ for → him."),
             ("Do you know ___?", "Bạn có biết cô ấy không?", ["she", "her", "hers"], 1, "Tân ngữ của know → her."),
             ("___ live in Hanoi.", "Họ sống ở Hà Nội.", ["Them", "They", "Their"], 1, "Chủ ngữ → They."),
             ("Please call ___ tomorrow.", "Hãy gọi cho chúng tôi ngày mai.", ["we", "us", "our"], 1, "Sau call → us."),
         ]),
    dict(level="A1", order=5, category="Câu hỏi", title_vi="Câu hỏi Wh-", title_en="Wh- questions",
         subtitle_vi="Cách đặt câu hỏi thông tin", form_vi="Câu hỏi · Từ để hỏi",
         formula="Wh- + do/does/be + S + V?",
         parts=[("Wh-", "Từ để hỏi"), ("do / does / be", "Trợ động từ"), ("S + V", "Chủ ngữ + Động từ")],
         note_vi="What = cái gì, Where = ở đâu, When = khi nào, Who = ai, Why = tại sao, How = thế nào.",
         explanation_vi="Câu hỏi Wh- hỏi thông tin cụ thể. Từ để hỏi đứng đầu, sau đó là trợ động từ (do/does hoặc am/is/are), rồi chủ ngữ và động từ nguyên mẫu.",
         mistake=("Bỏ trợ động từ do/does trong câu hỏi.", "Where you live?", "Where do you live?"),
         conjugation=[("What / Where / When", "cái gì / ở đâu / khi nào"), ("Who / Why / How", "ai / tại sao / thế nào"), ("Với to be", "Where is she? / How are you?")],
         examples=[("Where do you live?", "Bạn sống ở đâu?"), ("What is your name?", "Tên bạn là gì?"), ("Why does he study English?", "Tại sao anh ấy học tiếng Anh?")],
         exercises=[
             ("___ is your birthday?", "Sinh nhật bạn khi nào?", ["What", "When", "Where"], 1, "Hỏi thời gian → When."),
             ("___ do you go to work?", "Bạn đi làm bằng gì?", ["How", "Who", "What"], 0, "Hỏi cách thức → How."),
             ("Where ___ she come from?", "Cô ấy đến từ đâu?", ["do", "does", "is"], 1, "She → does."),
             ("___ is that man?", "Người đàn ông kia là ai?", ["Who", "What", "Why"], 0, "Hỏi người → Who."),
             ("What ___ you doing?", "Bạn đang làm gì?", ["do", "is", "are"], 2, "Tiếp diễn với you → are."),
             ("Why ___ they late?", "Tại sao họ đến muộn?", ["do", "are", "is"], 1, "They + tính từ late → are."),
             ("When ___ the class start?", "Lớp học bắt đầu khi nào?", ["do", "does", "are"], 1, "The class = it → does."),
             ("___ do you want, tea or coffee?", "Bạn muốn gì, trà hay cà phê?", ["Where", "Who", "What"], 2, "Hỏi vật → What."),
         ]),
    dict(level="A1", order=6, category="Cấu trúc", title_vi="There is / There are", title_en="There is / There are",
         subtitle_vi="Mô tả sự tồn tại của sự vật", form_vi="Thể khẳng định · Hiện tại đơn",
         formula="There + is/are + N",
         parts=[("There", "Có"), ("is / are", "Số ít / số nhiều"), ("N", "Danh từ")],
         note_vi="Nhìn danh từ ngay sau: số ít → is, số nhiều → are. Không dịch there thành 'ở đó'.",
         explanation_vi="There is/There are diễn tả sự tồn tại của người hoặc vật. There is + danh từ số ít / không đếm được; There are + danh từ số nhiều. Phủ định: There isn't / There aren't.",
         mistake=("Dùng have thay cho there is/are để nói 'có'.", "In my room have a bed", "There is a bed in my room"),
         conjugation=[("Số ít", "There is a cat."), ("Số nhiều", "There are two cats."), ("Phủ định", "There isn't / There aren't")],
         examples=[("There is a book on the table.", "Có một quyển sách trên bàn."), ("There are many students in the class.", "Có nhiều học sinh trong lớp."), ("There isn't any milk left.", "Không còn chút sữa nào.")],
         exercises=[
             ("There ___ a cat under the chair.", "Có một con mèo dưới ghế.", ["is", "are", "have"], 0, "a cat số ít → is."),
             ("There ___ three apples in the bag.", "Có ba quả táo trong túi.", ["is", "are", "has"], 1, "three apples số nhiều → are."),
             ("___ there a bank near here?", "Gần đây có ngân hàng không?", ["Is", "Are", "Do"], 0, "a bank số ít → Is there."),
             ("There ___ any water in the bottle.", "Không có chút nước nào trong chai.", ["isn't", "aren't", "not"], 0, "water không đếm được → isn't."),
             ("There ___ many people at the party.", "Có nhiều người ở bữa tiệc.", ["is", "were", "was"], 1, "Số nhiều, quá khứ → were."),
             ("___ there any questions?", "Có câu hỏi nào không?", ["Is", "Are", "Does"], 1, "questions số nhiều → Are there."),
             ("There ___ a lot of noise outside.", "Bên ngoài có nhiều tiếng ồn.", ["is", "are", "have"], 0, "noise không đếm được → is."),
             ("There ___ two windows in my room.", "Phòng tôi có hai cửa sổ.", ["is", "are", "has"], 1, "two windows → are."),
         ]),
    dict(level="A2", order=1, category="Thì", title_vi="Thì quá khứ đơn", title_en="Past simple",
         subtitle_vi="Kể lại việc đã xảy ra", form_vi="Thể khẳng định · Quá khứ đơn",
         formula="S + V2/V-ed + O",
         parts=[("S", "Chủ ngữ"), ("V2 / V-ed", "Động từ quá khứ"), ("O", "Tân ngữ")],
         note_vi="Động từ bất quy tắc phải học thuộc: go → went, eat → ate, see → saw.",
         explanation_vi="Thì quá khứ đơn diễn tả hành động đã xảy ra và kết thúc trong quá khứ, thường có mốc thời gian (yesterday, last week, in 2020). Động từ có quy tắc thêm -ed; bất quy tắc dùng cột 2.",
         mistake=("Thêm -ed vào động từ bất quy tắc.", "I goed to school yesterday", "I went to school yesterday"),
         conjugation=[("Có quy tắc", "work → worked, play → played"), ("Bất quy tắc", "go → went, have → had"), ("Phủ định", "didn't + V nguyên mẫu")],
         examples=[("I visited my grandmother last week.", "Tuần trước tôi thăm bà."), ("She went to Da Nang in 2023.", "Cô ấy đi Đà Nẵng năm 2023."), ("We didn't watch the movie.", "Chúng tôi đã không xem bộ phim đó.")],
         exercises=[
             ("I ___ a great time yesterday.", "Hôm qua tôi đã có khoảng thời gian tuyệt vời.", ["have", "had", "has"], 1, "have → had."),
             ("She ___ to Paris last year.", "Năm ngoái cô ấy đi Paris.", ["go", "goed", "went"], 2, "go → went."),
             ("They ___ football on Sunday.", "Chủ nhật họ đã chơi bóng.", ["play", "played", "plays"], 1, "play + ed."),
             ("He ___ come to the party.", "Anh ấy đã không đến bữa tiệc.", ["didn't", "doesn't", "wasn't"], 0, "Phủ định quá khứ → didn't + V."),
             ("We ___ a movie last night.", "Tối qua chúng tôi xem phim.", ["see", "saw", "seen"], 1, "see → saw."),
             ("I ___ my homework before dinner.", "Tôi làm bài tập trước bữa tối.", ["do", "did", "done"], 1, "do → did."),
             ("___ you call her yesterday?", "Hôm qua bạn có gọi cô ấy không?", ["Do", "Did", "Were"], 1, "Câu hỏi quá khứ → Did."),
             ("The bus ___ late this morning.", "Sáng nay xe buýt đến muộn.", ["is", "was", "were"], 1, "The bus = it, quá khứ → was."),
         ]),
    dict(level="A2", order=2, category="Thì", title_vi="Thì hiện tại tiếp diễn", title_en="Present continuous",
         subtitle_vi="Hành động đang diễn ra", form_vi="Thể khẳng định · Hiện tại tiếp diễn",
         formula="S + be + V-ing",
         parts=[("S", "Chủ ngữ"), ("be", "am / is / are"), ("V-ing", "Động từ + ing")],
         note_vi="Luôn có to be trước V-ing — 'I studying' là câu thiếu động từ!",
         explanation_vi="Thì hiện tại tiếp diễn diễn tả hành động đang xảy ra tại lúc nói hoặc quanh thời điểm nói (now, at the moment, these days). Cấu trúc: be (am/is/are) + V-ing.",
         mistake=("Bỏ to be trước V-ing.", "She cooking dinner now", "She is cooking dinner now"),
         conjugation=[("I", "am working"), ("He / She / It", "is working"), ("You / We / They", "are working")],
         examples=[("I am learning English now.", "Bây giờ tôi đang học tiếng Anh."), ("She is cooking dinner.", "Cô ấy đang nấu bữa tối."), ("They are playing in the garden.", "Bọn trẻ đang chơi trong vườn.")],
         exercises=[
             ("Look! It ___ raining.", "Nhìn kìa! Trời đang mưa.", ["is", "are", "am"], 0, "It → is + raining."),
             ("They ___ watching TV now.", "Họ đang xem TV.", ["is", "are", "am"], 1, "They → are."),
             ("I ___ reading a good book.", "Tôi đang đọc một cuốn sách hay.", ["is", "are", "am"], 2, "I → am."),
             ("She is ___ to music.", "Cô ấy đang nghe nhạc.", ["listen", "listens", "listening"], 2, "Sau is → V-ing."),
             ("What ___ you doing?", "Bạn đang làm gì?", ["is", "are", "do"], 1, "You → are."),
             ("We ___ not sleeping.", "Chúng tôi không ngủ.", ["is", "am", "are"], 2, "We → are not."),
             ("He is ___ his homework.", "Anh ấy đang làm bài tập.", ["do", "doing", "does"], 1, "is + doing."),
             ("The children ___ playing outside.", "Bọn trẻ đang chơi bên ngoài.", ["is", "are", "am"], 1, "The children số nhiều → are."),
         ]),
]
# fmt: on
