"""Bảng 44 âm IPA tiếng Anh (RP/GA) kèm mô tả tiếng Việt — nguồn seed cho `seed_ipa`.

Mỗi mục: symbol, group, category (vi/en), mô tả ngắn, khẩu hình (môi/lưỡi + đoạn văn),
mẹo, từ mẫu (word/ipa/meaning) và cặp âm tối thiểu. Thứ tự trong danh sách = `order`.
"""

# fmt: off
VOWELS = [
    # ---- Nguyên âm đơn (12)
    dict(symbol="iː", group="monophthong", category_vi="Nguyên âm dài", category_en="Long Vowel",
         description_vi="Khẩu hình dẹt, phát âm ngân dài và thanh thoát",
         lips_vi="Bè dẹt", tongue_vi="Hơi nâng cao",
         articulation_vi="Kéo dài luồng hơi, môi hơi dẹt, hai khóe miệng bè rộng sang hai bên như khi mỉm cười nhẹ. Thân lưỡi nâng cao chạm gần vòm miệng trên.",
         tip_vi="Âm /iː/ kéo dài tầm 1,5 lần so với /ɪ/, và hai khóe miệng nhớ kéo sang như đang cười nhé!",
         examples=[("sheep", "/ʃiːp/", "con cừu"), ("see", "/siː/", "nhìn thấy"), ("tea", "/tiː/", "trà"), ("green", "/ɡriːn/", "màu xanh lá")],
         pair=("ɪ", ["sheep", "ship"])),
    dict(symbol="ɪ", group="monophthong", category_vi="Nguyên âm ngắn", category_en="Short Vowel",
         description_vi="Âm ngắn, dứt khoát, miệng hơi mở",
         lips_vi="Thả lỏng", tongue_vi="Nâng vừa, hơi lùi",
         articulation_vi="Môi thả lỏng, không bè rộng. Lưỡi nâng vừa phải và lùi nhẹ so với /iː/. Phát âm ngắn, dứt khoát, không kéo dài.",
         tip_vi="Đừng cười khi nói /ɪ/ — miệng thả lỏng, âm bật ra rồi dừng ngay.",
         examples=[("ship", "/ʃɪp/", "con tàu"), ("sit", "/sɪt/", "ngồi"), ("big", "/bɪɡ/", "to lớn"), ("fish", "/fɪʃ/", "con cá")],
         pair=("iː", ["ship", "sheep"])),
    dict(symbol="e", group="monophthong", category_vi="Nguyên âm ngắn", category_en="Short Vowel",
         description_vi="Miệng mở vừa, lưỡi ở giữa, âm ngắn gọn",
         lips_vi="Mở vừa", tongue_vi="Giữa, hơi nâng",
         articulation_vi="Miệng mở vừa phải, môi hơi kéo ngang. Đầu lưỡi chạm nhẹ răng dưới, thân lưỡi ở vị trí giữa. Âm phát ra ngắn và gọn.",
         tip_vi="Nghĩ đến chữ 'e' trong 'em bé' nhưng ngắn hơn và không ngân.",
         examples=[("bed", "/bed/", "cái giường"), ("red", "/red/", "màu đỏ"), ("ten", "/ten/", "số mười"), ("head", "/hed/", "cái đầu")],
         pair=("æ", ["bed", "bad"])),
    dict(symbol="æ", group="monophthong", category_vi="Nguyên âm ngắn", category_en="Short Vowel",
         description_vi="Miệng mở rộng, hàm hạ thấp, âm sáng",
         lips_vi="Mở rộng", tongue_vi="Hạ thấp, đưa trước",
         articulation_vi="Hạ hàm xuống rộng hơn /e/, môi kéo ngang. Lưỡi hạ thấp và đưa về phía trước. Âm sáng, hơi giống 'a' pha 'e' của tiếng Việt.",
         tip_vi="Hạ hàm như sắp cắn quả táo — /æ/ cần miệng mở rộng hơn bạn nghĩ!",
         examples=[("cat", "/kæt/", "con mèo"), ("bad", "/bæd/", "tệ, xấu"), ("hat", "/hæt/", "cái mũ"), ("apple", "/ˈæp.əl/", "quả táo")],
         pair=("e", ["bad", "bed"])),
    dict(symbol="ɑː", group="monophthong", category_vi="Nguyên âm dài", category_en="Long Vowel",
         description_vi="Miệng mở to, âm trầm và kéo dài từ cổ họng",
         lips_vi="Mở tròn rộng", tongue_vi="Hạ thấp, lùi sau",
         articulation_vi="Mở miệng to, hàm hạ hết cỡ. Lưỡi hạ thấp và lùi về phía sau, âm phát ra từ sâu trong cổ họng và kéo dài.",
         tip_vi="Giống khi bác sĩ bảo bạn 'Aaa' để khám họng — dài và mở rộng.",
         examples=[("car", "/kɑːr/", "xe hơi"), ("father", "/ˈfɑː.ðər/", "bố"), ("start", "/stɑːrt/", "bắt đầu"), ("heart", "/hɑːrt/", "trái tim")],
         pair=("ʌ", ["cart", "cut"])),
    dict(symbol="ɒ", group="monophthong", category_vi="Nguyên âm ngắn", category_en="Short Vowel",
         description_vi="Môi tròn, miệng mở, âm ngắn (giọng Anh)",
         lips_vi="Tròn nhẹ", tongue_vi="Hạ thấp, lùi sau",
         articulation_vi="Môi hơi tròn, hàm mở khá rộng. Lưỡi hạ thấp và lùi sau. Âm ngắn; giọng Mỹ thường phát thành /ɑː/.",
         tip_vi="Giọng Anh: 'hot' nghe tròn miệng; giọng Mỹ: gần như 'haat'. Cả hai đều đúng!",
         examples=[("hot", "/hɒt/", "nóng"), ("dog", "/dɒɡ/", "con chó"), ("box", "/bɒks/", "cái hộp"), ("clock", "/klɒk/", "đồng hồ")],
         pair=("ɔː", ["cot", "caught"])),
    dict(symbol="ɔː", group="monophthong", category_vi="Nguyên âm dài", category_en="Long Vowel",
         description_vi="Môi tròn chụm, âm dài và vang",
         lips_vi="Tròn chụm", tongue_vi="Lùi sau, nâng nhẹ",
         articulation_vi="Chụm tròn môi như sắp huýt sáo nhưng mở hơn. Lưỡi lùi về sau, phần sau lưỡi nâng nhẹ. Kéo dài âm.",
         tip_vi="Tròn môi và giữ âm lâu như tiếng 'o' trong 'ô tô' kéo dài.",
         examples=[("door", "/dɔːr/", "cửa"), ("talk", "/tɔːk/", "nói chuyện"), ("more", "/mɔːr/", "nhiều hơn"), ("water", "/ˈwɔː.tər/", "nước")],
         pair=("ɒ", ["caught", "cot"])),
    dict(symbol="ʊ", group="monophthong", category_vi="Nguyên âm ngắn", category_en="Short Vowel",
         description_vi="Môi hơi tròn, âm ngắn và thả lỏng",
         lips_vi="Tròn nhẹ, thả lỏng", tongue_vi="Nâng sau, thả lỏng",
         articulation_vi="Môi tròn nhẹ nhưng không chụm chặt. Phần sau lưỡi nâng lên, cơ mặt thả lỏng. Âm rất ngắn.",
         tip_vi="Giống 'u' nhưng lười biếng hơn — miệng không chụm hẳn, âm dừng ngay.",
         examples=[("book", "/bʊk/", "quyển sách"), ("good", "/ɡʊd/", "tốt"), ("put", "/pʊt/", "đặt"), ("foot", "/fʊt/", "bàn chân")],
         pair=("uː", ["pull", "pool"])),
    dict(symbol="uː", group="monophthong", category_vi="Nguyên âm dài", category_en="Long Vowel",
         description_vi="Môi chụm tròn, âm dài như huýt sáo",
         lips_vi="Chụm tròn chặt", tongue_vi="Nâng cao phía sau",
         articulation_vi="Chụm tròn môi chặt, đẩy hơi ra phía trước. Phần sau lưỡi nâng cao. Kéo dài âm, giữ môi tròn suốt thời gian.",
         tip_vi="Chu môi như sắp huýt sáo rồi ngân 'uuu' — đó chính là /uː/.",
         examples=[("moon", "/muːn/", "mặt trăng"), ("blue", "/bluː/", "màu xanh dương"), ("food", "/fuːd/", "thức ăn"), ("school", "/skuːl/", "trường học")],
         pair=("ʊ", ["pool", "pull"])),
    dict(symbol="ʌ", group="monophthong", category_vi="Nguyên âm ngắn", category_en="Short Vowel",
         description_vi="Miệng mở vừa, âm ngắn, phát từ giữa khoang miệng",
         lips_vi="Thả lỏng, mở vừa", tongue_vi="Giữa, hơi hạ",
         articulation_vi="Miệng mở vừa, môi thả lỏng không tròn. Lưỡi nằm ở giữa và hơi hạ. Âm ngắn, gần giống 'ă' tiếng Việt.",
         tip_vi="Nghĩ đến 'ă' trong 'ăn' — ngắn, dứt khoát, không tròn môi.",
         examples=[("cup", "/kʌp/", "cái cốc"), ("sun", "/sʌn/", "mặt trời"), ("love", "/lʌv/", "yêu"), ("money", "/ˈmʌn.i/", "tiền")],
         pair=("ɑː", ["cut", "cart"])),
    dict(symbol="ɜː", group="monophthong", category_vi="Nguyên âm dài", category_en="Long Vowel",
         description_vi="Âm dài ở giữa miệng, môi trung tính",
         lips_vi="Trung tính", tongue_vi="Giữa, cuốn nhẹ (US)",
         articulation_vi="Môi ở vị trí trung tính, không tròn không bè. Lưỡi nằm giữa khoang miệng, giọng Mỹ cuốn nhẹ đầu lưỡi. Kéo dài âm.",
         tip_vi="Giống 'ơ' kéo dài; giọng Mỹ thêm chút cuốn lưỡi thành 'ơr'.",
         examples=[("bird", "/bɜːrd/", "con chim"), ("girl", "/ɡɜːrl/", "cô gái"), ("work", "/wɜːrk/", "làm việc"), ("learn", "/lɜːrn/", "học")],
         pair=("ɔː", ["bird", "board"])),
    dict(symbol="ə", group="monophthong", category_vi="Âm schwa", category_en="Schwa",
         description_vi="Âm yếu nhất, luôn ở âm tiết không nhấn",
         lips_vi="Thả lỏng hoàn toàn", tongue_vi="Giữa, nghỉ",
         articulation_vi="Toàn bộ cơ miệng thả lỏng, môi hé nhẹ, lưỡi ở vị trí nghỉ. Âm rất ngắn và nhẹ, chỉ xuất hiện ở âm tiết không nhấn.",
         tip_vi="Schwa là âm 'lười' nhất tiếng Anh — càng nhẹ càng đúng!",
         examples=[("banana", "/bəˈnɑː.nə/", "quả chuối"), ("about", "/əˈbaʊt/", "về"), ("teacher", "/ˈtiː.tʃər/", "giáo viên"), ("sofa", "/ˈsəʊ.fə/", "ghế sofa")],
         pair=("ɜː", ["forward", "word"])),
    # ---- Nguyên âm đôi (8)
    dict(symbol="eɪ", group="diphthong", category_vi="Nguyên âm đôi", category_en="Diphthong",
         description_vi="Trượt từ /e/ sang /ɪ/, kết thúc bằng khóe miệng bè",
         lips_vi="Mở vừa → bè", tongue_vi="Giữa → nâng cao",
         articulation_vi="Bắt đầu ở /e/ với miệng mở vừa, rồi trượt nhanh lên /ɪ/ — lưỡi nâng cao, khóe miệng kéo sang. Âm đầu dài hơn âm sau.",
         tip_vi="Đừng nói 'ê' phẳng: 'day' phải có cái đuôi 'i' nhỏ ở cuối.",
         examples=[("day", "/deɪ/", "ngày"), ("name", "/neɪm/", "tên"), ("rain", "/reɪn/", "mưa"), ("play", "/pleɪ/", "chơi")],
         pair=("e", ["pain", "pen"])),
    dict(symbol="aɪ", group="diphthong", category_vi="Nguyên âm đôi", category_en="Diphthong",
         description_vi="Trượt từ /a/ mở rộng sang /ɪ/",
         lips_vi="Mở rộng → hẹp", tongue_vi="Thấp → nâng cao",
         articulation_vi="Mở miệng rộng ở /a/, sau đó lưỡi nâng nhanh lên /ɪ/ và miệng khép dần. Trọng tâm ở âm đầu.",
         tip_vi="Giống 'ai' tiếng Việt nhưng phần 'a' mở rộng và dài hơn.",
         examples=[("my", "/maɪ/", "của tôi"), ("time", "/taɪm/", "thời gian"), ("light", "/laɪt/", "ánh sáng"), ("five", "/faɪv/", "số năm")],
         pair=("eɪ", ["my", "may"])),
    dict(symbol="ɔɪ", group="diphthong", category_vi="Nguyên âm đôi", category_en="Diphthong",
         description_vi="Trượt từ /ɔ/ tròn môi sang /ɪ/",
         lips_vi="Tròn → bè", tongue_vi="Lùi sau → nâng trước",
         articulation_vi="Bắt đầu với môi tròn ở /ɔ/, rồi môi mở bè và lưỡi tiến lên phía trước tới /ɪ/. Chuyển động môi rõ rệt.",
         tip_vi="Từ tròn môi sang cười — 'boy' là một cú chuyển môi nhỏ.",
         examples=[("boy", "/bɔɪ/", "cậu bé"), ("toy", "/tɔɪ/", "đồ chơi"), ("coin", "/kɔɪn/", "đồng xu"), ("enjoy", "/ɪnˈdʒɔɪ/", "tận hưởng")],
         pair=("aɪ", ["boy", "buy"])),
    dict(symbol="əʊ", group="diphthong", category_vi="Nguyên âm đôi", category_en="Diphthong",
         description_vi="Trượt từ /ə/ sang /ʊ/, kết thúc tròn môi",
         lips_vi="Trung tính → tròn", tongue_vi="Giữa → nâng sau",
         articulation_vi="Bắt đầu ở schwa với môi thả lỏng, rồi chụm tròn môi dần về /ʊ/. Giọng Mỹ bắt đầu bằng /o/ tròn hơn (/oʊ/).",
         tip_vi="Không phải 'ô' phẳng — 'go' kết thúc bằng môi chụm tròn nhẹ.",
         examples=[("go", "/ɡəʊ/", "đi"), ("home", "/həʊm/", "nhà"), ("no", "/nəʊ/", "không"), ("phone", "/fəʊn/", "điện thoại")],
         pair=("ɔː", ["coat", "caught"])),
    dict(symbol="aʊ", group="diphthong", category_vi="Nguyên âm đôi", category_en="Diphthong",
         description_vi="Trượt từ /a/ mở rộng sang /ʊ/ tròn môi",
         lips_vi="Mở rộng → tròn", tongue_vi="Thấp → nâng sau",
         articulation_vi="Mở miệng rộng ở /a/, sau đó chụm tròn môi và nâng phần sau lưỡi tới /ʊ/. Hai chuyển động môi rõ.",
         tip_vi="Giống 'ao' tiếng Việt nhưng mở đầu rộng hơn và kết thúc chụm môi hơn.",
         examples=[("now", "/naʊ/", "bây giờ"), ("house", "/haʊs/", "ngôi nhà"), ("down", "/daʊn/", "xuống"), ("cloud", "/klaʊd/", "đám mây")],
         pair=("əʊ", ["now", "know"])),
    dict(symbol="ɪə", group="diphthong", category_vi="Nguyên âm đôi", category_en="Diphthong",
         description_vi="Trượt từ /ɪ/ sang schwa (giọng Anh)",
         lips_vi="Hẹp → thả lỏng", tongue_vi="Nâng cao → giữa",
         articulation_vi="Bắt đầu ở /ɪ/ rồi thả lỏng dần về schwa. Giọng Anh giữ nguyên; giọng Mỹ phát thành /ɪr/ có cuốn lưỡi.",
         tip_vi="'here' giọng Anh là 'hi-ơ'; giọng Mỹ là 'hi-r'.",
         examples=[("here", "/hɪər/", "ở đây"), ("ear", "/ɪər/", "cái tai"), ("near", "/nɪər/", "gần"), ("year", "/jɪər/", "năm")],
         pair=("eə", ["here", "hair"])),
    dict(symbol="eə", group="diphthong", category_vi="Nguyên âm đôi", category_en="Diphthong",
         description_vi="Trượt từ /e/ sang schwa (giọng Anh)",
         lips_vi="Mở vừa → thả lỏng", tongue_vi="Giữa, hơi hạ",
         articulation_vi="Bắt đầu ở /e/ miệng mở vừa rồi thả lỏng về schwa. Giọng Mỹ phát thành /er/ với cuốn lưỡi.",
         tip_vi="'hair' giọng Anh nghe như 'he-ơ', giọng Mỹ như 'her' mở hơn.",
         examples=[("hair", "/heər/", "tóc"), ("care", "/keər/", "quan tâm"), ("where", "/weər/", "ở đâu"), ("chair", "/tʃeər/", "cái ghế")],
         pair=("ɪə", ["hair", "here"])),
    dict(symbol="ʊə", group="diphthong", category_vi="Nguyên âm đôi", category_en="Diphthong",
         description_vi="Trượt từ /ʊ/ tròn môi sang schwa (giọng Anh)",
         lips_vi="Tròn → thả lỏng", tongue_vi="Nâng sau → giữa",
         articulation_vi="Bắt đầu với môi tròn nhẹ ở /ʊ/ rồi thả lỏng về schwa. Nhiều người Anh hiện đọc thành /ɔː/; giọng Mỹ là /ʊr/.",
         tip_vi="'tour' = 'tu-ơ'. Âm này hiếm, gặp chủ yếu trong 'tour', 'pure', 'sure'.",
         examples=[("tour", "/tʊər/", "chuyến du lịch"), ("pure", "/pjʊər/", "tinh khiết"), ("sure", "/ʃʊər/", "chắc chắn"), ("cure", "/kjʊər/", "chữa trị")],
         pair=("ɔː", ["tour", "tore"])),
]

CONSONANTS = [
    # ---- Phụ âm vô thanh (9)
    dict(symbol="p", group="voiceless", category_vi="Phụ âm bật hơi vô thanh", category_en="Voiceless Plosive",
         description_vi="Hai môi khép rồi bật hơi mạnh, không rung thanh quản",
         lips_vi="Khép chặt rồi bật", tongue_vi="Nghỉ",
         articulation_vi="Khép chặt hai môi, tích hơi rồi bật ra mạnh. Không rung dây thanh. Ở đầu từ có luồng hơi mạnh (đặt tay trước miệng sẽ thấy gió).",
         tip_vi="Đặt tờ giấy trước miệng: nói 'pen' đúng thì giấy phải bay!",
         examples=[("pen", "/pen/", "cây bút"), ("apple", "/ˈæp.əl/", "quả táo"), ("stop", "/stɒp/", "dừng lại"), ("happy", "/ˈhæp.i/", "vui vẻ")],
         pair=("b", ["pen", "Ben"])),
    dict(symbol="t", group="voiceless", category_vi="Phụ âm bật hơi vô thanh", category_en="Voiceless Plosive",
         description_vi="Đầu lưỡi chạm nướu trên rồi bật hơi",
         lips_vi="Hé mở", tongue_vi="Đầu lưỡi chạm nướu trên",
         articulation_vi="Đặt đầu lưỡi vào nướu ngay sau răng cửa trên, chặn hơi rồi bật ra. Không rung dây thanh. Cuối từ vẫn phải bật nhẹ.",
         tip_vi="Khác 't' tiếng Việt: lưỡi chạm nướu chứ không chạm răng, và có bật hơi.",
         examples=[("ten", "/ten/", "số mười"), ("time", "/taɪm/", "thời gian"), ("cat", "/kæt/", "con mèo"), ("water", "/ˈwɔː.tər/", "nước")],
         pair=("d", ["ten", "den"])),
    dict(symbol="k", group="voiceless", category_vi="Phụ âm bật hơi vô thanh", category_en="Voiceless Plosive",
         description_vi="Cuống lưỡi chạm vòm mềm rồi bật hơi",
         lips_vi="Mở tự nhiên", tongue_vi="Cuống lưỡi nâng chạm vòm mềm",
         articulation_vi="Nâng phần sau lưỡi chạm vòm mềm, chặn hơi rồi bật ra. Không rung dây thanh. Đầu từ bật hơi mạnh.",
         tip_vi="Giống 'c/k' tiếng Việt nhưng nhớ bật hơi mạnh ở đầu từ ('key' chứ không 'ki').",
         examples=[("key", "/kiː/", "chìa khóa"), ("cat", "/kæt/", "con mèo"), ("book", "/bʊk/", "quyển sách"), ("school", "/skuːl/", "trường học")],
         pair=("ɡ", ["coat", "goat"])),
    dict(symbol="f", group="voiceless", category_vi="Phụ âm xát vô thanh", category_en="Voiceless Fricative",
         description_vi="Răng trên chạm môi dưới, hơi xát qua khe",
         lips_vi="Răng trên đặt lên môi dưới", tongue_vi="Nghỉ",
         articulation_vi="Đặt răng cửa trên lên môi dưới, đẩy hơi xát qua khe hở. Không rung dây thanh. Có thể kéo dài âm.",
         tip_vi="Giống 'ph' tiếng Việt — hãy để răng thật sự chạm môi dưới.",
         examples=[("fish", "/fɪʃ/", "con cá"), ("coffee", "/ˈkɒf.i/", "cà phê"), ("leaf", "/liːf/", "chiếc lá"), ("phone", "/fəʊn/", "điện thoại")],
         pair=("v", ["fan", "van"])),
    dict(symbol="θ", group="voiceless", category_vi="Phụ âm xát vô thanh", category_en="Voiceless Fricative",
         description_vi="Đầu lưỡi đặt giữa hai hàm răng, thổi hơi",
         lips_vi="Hé mở", tongue_vi="Đầu lưỡi kẹp nhẹ giữa răng",
         articulation_vi="Đưa đầu lưỡi ra kẹp nhẹ giữa hai hàm răng, thổi hơi xát qua. Không rung dây thanh. Người Việt hay thay bằng /t/ hoặc /s/ — sai.",
         tip_vi="Soi gương: phải thấy đầu lưỡi ló ra giữa răng khi nói 'think'.",
         examples=[("think", "/θɪŋk/", "nghĩ"), ("three", "/θriː/", "số ba"), ("bath", "/bɑːθ/", "bồn tắm"), ("mouth", "/maʊθ/", "cái miệng")],
         pair=("ð", ["thigh", "thy"])),
    dict(symbol="s", group="voiceless", category_vi="Phụ âm xát vô thanh", category_en="Voiceless Fricative",
         description_vi="Đầu lưỡi gần nướu trên, hơi rít qua khe hẹp",
         lips_vi="Hé, hơi bè", tongue_vi="Đầu lưỡi sát nướu trên",
         articulation_vi="Đưa đầu lưỡi gần nướu trên (không chạm), tạo khe hẹp cho hơi rít qua. Không rung dây thanh. Kéo dài được như tiếng rắn.",
         tip_vi="Nhớ phát âm 's' ở cuối từ số nhiều: 'cats' phải nghe rõ tiếng 'sss'.",
         examples=[("sun", "/sʌn/", "mặt trời"), ("see", "/siː/", "nhìn thấy"), ("bus", "/bʌs/", "xe buýt"), ("class", "/klɑːs/", "lớp học")],
         pair=("z", ["sip", "zip"])),
    dict(symbol="ʃ", group="voiceless", category_vi="Phụ âm xát vô thanh", category_en="Voiceless Fricative",
         description_vi="Môi hơi chu, lưỡi lùi sau, hơi xát rộng",
         lips_vi="Chu nhẹ ra trước", tongue_vi="Lùi sau, mặt lưỡi nâng",
         articulation_vi="Chu môi nhẹ về phía trước, lưỡi lùi sau so với /s/, mặt lưỡi nâng lên gần vòm. Hơi xát qua khe rộng hơn /s/. Không rung dây thanh.",
         tip_vi="Đây là âm 'suỵt' bảo im lặng — chu môi rồi thổi.",
         examples=[("ship", "/ʃɪp/", "con tàu"), ("she", "/ʃiː/", "cô ấy"), ("fish", "/fɪʃ/", "con cá"), ("nation", "/ˈneɪ.ʃən/", "quốc gia")],
         pair=("s", ["ship", "sip"])),
    dict(symbol="tʃ", group="voiceless", category_vi="Phụ âm tắc xát vô thanh", category_en="Voiceless Affricate",
         description_vi="Bắt đầu như /t/ rồi bung thành /ʃ/",
         lips_vi="Chu nhẹ", tongue_vi="Chạm nướu rồi lùi",
         articulation_vi="Đặt đầu lưỡi vào nướu trên như /t/, chặn hơi rồi thả ra thành tiếng xát /ʃ/. Hai âm dính liền thành một. Không rung dây thanh.",
         tip_vi="Giống 'ch' tiếng Việt nhưng có bật hơi mạnh hơn.",
         examples=[("chair", "/tʃeər/", "cái ghế"), ("cheese", "/tʃiːz/", "phô mai"), ("teacher", "/ˈtiː.tʃər/", "giáo viên"), ("watch", "/wɒtʃ/", "đồng hồ đeo tay")],
         pair=("dʒ", ["cheap", "jeep"])),
    dict(symbol="h", group="voiceless", category_vi="Phụ âm xát vô thanh", category_en="Voiceless Fricative",
         description_vi="Hơi thở nhẹ thoát ra từ cổ họng",
         lips_vi="Theo nguyên âm sau", tongue_vi="Nghỉ",
         articulation_vi="Thở nhẹ ra từ cổ họng, miệng ở tư thế của nguyên âm đi sau. Không rung dây thanh. Rất nhẹ, không khàn.",
         tip_vi="Như hà hơi vào gương — nhẹ thôi, đừng khàn cổ.",
         examples=[("hat", "/hæt/", "cái mũ"), ("house", "/haʊs/", "ngôi nhà"), ("hello", "/həˈləʊ/", "xin chào"), ("behind", "/bɪˈhaɪnd/", "phía sau")],
         pair=("", ["hat", "at"])),
    # ---- Phụ âm hữu thanh (8)
    dict(symbol="b", group="voiced", category_vi="Phụ âm bật hơi hữu thanh", category_en="Voiced Plosive",
         description_vi="Hai môi khép rồi bật, có rung thanh quản",
         lips_vi="Khép chặt rồi bật", tongue_vi="Nghỉ",
         articulation_vi="Khép chặt hai môi rồi bật ra như /p/ nhưng dây thanh rung. Luồng hơi yếu hơn /p/. Đặt tay lên cổ sẽ thấy rung.",
         tip_vi="Tay đặt lên cổ: 'b' rung, 'p' không rung — đó là khác biệt duy nhất.",
         examples=[("bed", "/bed/", "cái giường"), ("baby", "/ˈbeɪ.bi/", "em bé"), ("job", "/dʒɒb/", "công việc"), ("table", "/ˈteɪ.bəl/", "cái bàn")],
         pair=("p", ["bat", "pat"])),
    dict(symbol="d", group="voiced", category_vi="Phụ âm bật hơi hữu thanh", category_en="Voiced Plosive",
         description_vi="Đầu lưỡi chạm nướu trên rồi bật, có rung",
         lips_vi="Hé mở", tongue_vi="Đầu lưỡi chạm nướu trên",
         articulation_vi="Đặt đầu lưỡi vào nướu trên như /t/, chặn hơi rồi bật ra với dây thanh rung. Cuối từ vẫn phải nghe rõ (không nuốt).",
         tip_vi="Cuối từ 'bad' vẫn phải có 'd' nhẹ — đừng đọc thành 'ba'.",
         examples=[("dog", "/dɒɡ/", "con chó"), ("day", "/deɪ/", "ngày"), ("bad", "/bæd/", "tệ"), ("ladder", "/ˈlæd.ər/", "cái thang")],
         pair=("t", ["den", "ten"])),
    dict(symbol="ɡ", group="voiced", category_vi="Phụ âm bật hơi hữu thanh", category_en="Voiced Plosive",
         description_vi="Cuống lưỡi chạm vòm mềm rồi bật, có rung",
         lips_vi="Mở tự nhiên", tongue_vi="Cuống lưỡi chạm vòm mềm",
         articulation_vi="Nâng phần sau lưỡi chạm vòm mềm như /k/, bật ra với dây thanh rung. Luồng hơi yếu hơn /k/.",
         tip_vi="Giống 'g' trong 'gà' — nhưng nhớ cuối từ 'big' vẫn phải bật 'g'.",
         examples=[("go", "/ɡəʊ/", "đi"), ("green", "/ɡriːn/", "xanh lá"), ("big", "/bɪɡ/", "to lớn"), ("egg", "/eɡ/", "quả trứng")],
         pair=("k", ["goat", "coat"])),
    dict(symbol="v", group="voiced", category_vi="Phụ âm xát hữu thanh", category_en="Voiced Fricative",
         description_vi="Răng trên chạm môi dưới, hơi xát và rung",
         lips_vi="Răng trên đặt lên môi dưới", tongue_vi="Nghỉ",
         articulation_vi="Đặt răng trên lên môi dưới như /f/ nhưng dây thanh rung. Người Việt hay đọc thành /v/ giọng Bắc hoặc /j/ giọng Nam — phải có răng chạm môi.",
         tip_vi="'v' tiếng Anh = 'ph' có rung. Đừng đọc 'very' thành 'dery' hay 'wery'.",
         examples=[("van", "/væn/", "xe tải nhỏ"), ("very", "/ˈver.i/", "rất"), ("love", "/lʌv/", "yêu"), ("seven", "/ˈsev.ən/", "số bảy")],
         pair=("f", ["van", "fan"])),
    dict(symbol="ð", group="voiced", category_vi="Phụ âm xát hữu thanh", category_en="Voiced Fricative",
         description_vi="Đầu lưỡi giữa hai hàm răng, hơi xát và rung",
         lips_vi="Hé mở", tongue_vi="Đầu lưỡi kẹp nhẹ giữa răng",
         articulation_vi="Kẹp nhẹ đầu lưỡi giữa hai hàm răng như /θ/ nhưng dây thanh rung. Người Việt hay thay bằng /d/ hoặc /z/ — sai.",
         tip_vi="'the', 'this', 'that' đều là âm này — lưỡi phải ló ra giữa răng!",
         examples=[("this", "/ðɪs/", "cái này"), ("the", "/ðə/", "(mạo từ)"), ("mother", "/ˈmʌð.ər/", "mẹ"), ("breathe", "/briːð/", "hít thở")],
         pair=("θ", ["thy", "thigh"])),
    dict(symbol="z", group="voiced", category_vi="Phụ âm xát hữu thanh", category_en="Voiced Fricative",
         description_vi="Như /s/ nhưng có rung thanh quản",
         lips_vi="Hé, hơi bè", tongue_vi="Đầu lưỡi sát nướu trên",
         articulation_vi="Đặt lưỡi như /s/, đẩy hơi qua khe hẹp và rung dây thanh — như tiếng ong bay. Đuôi số nhiều 'dogs', 'is', 'was' đều là /z/.",
         tip_vi="'zzz' như ong vo ve. 'is' đọc là /ɪz/, không phải 'is-s'.",
         examples=[("zoo", "/zuː/", "sở thú"), ("zero", "/ˈzɪə.rəʊ/", "số không"), ("busy", "/ˈbɪz.i/", "bận"), ("dogs", "/dɒɡz/", "những con chó")],
         pair=("s", ["zip", "sip"])),
    dict(symbol="ʒ", group="voiced", category_vi="Phụ âm xát hữu thanh", category_en="Voiced Fricative",
         description_vi="Như /ʃ/ nhưng có rung, thường ở giữa từ",
         lips_vi="Chu nhẹ ra trước", tongue_vi="Lùi sau, mặt lưỡi nâng",
         articulation_vi="Đặt môi và lưỡi như /ʃ/ ('suỵt') rồi rung dây thanh. Hiếm khi đứng đầu từ; gặp trong 'usual', 'vision', 'measure'.",
         tip_vi="Giống 'gi' giọng Bắc nhưng chu môi hơn — 'measure' = 'me-giơ'.",
         examples=[("vision", "/ˈvɪʒ.ən/", "tầm nhìn"), ("measure", "/ˈmeʒ.ər/", "đo lường"), ("usual", "/ˈjuː.ʒu.əl/", "thường lệ"), ("garage", "/ˈɡær.ɑːʒ/", "ga-ra")],
         pair=("ʃ", ["vision", "mission"])),
    dict(symbol="dʒ", group="voiced", category_vi="Phụ âm tắc xát hữu thanh", category_en="Voiced Affricate",
         description_vi="Bắt đầu như /d/ rồi bung thành /ʒ/",
         lips_vi="Chu nhẹ", tongue_vi="Chạm nướu rồi lùi",
         articulation_vi="Đặt đầu lưỡi vào nướu trên như /d/, chặn hơi rồi thả ra thành /ʒ/ với dây thanh rung. Hai âm dính liền.",
         tip_vi="Giống 'j' trong 'jam' — 'gi' tiếng Việt nhưng bật mạnh hơn và có rung.",
         examples=[("job", "/dʒɒb/", "công việc"), ("juice", "/dʒuːs/", "nước ép"), ("age", "/eɪdʒ/", "tuổi"), ("bridge", "/brɪdʒ/", "cây cầu")],
         pair=("tʃ", ["jeep", "cheap"])),
    # ---- Âm mũi & bán nguyên âm (7)
    dict(symbol="m", group="nasal_approx", category_vi="Phụ âm mũi", category_en="Nasal",
         description_vi="Hai môi khép, hơi thoát qua mũi",
         lips_vi="Khép kín", tongue_vi="Nghỉ",
         articulation_vi="Khép kín hai môi, dây thanh rung và hơi thoát ra qua mũi. Cuối từ vẫn phải khép môi rõ ('same' ≠ 'say').",
         tip_vi="Bịt mũi lại mà nói 'mmm' không được — đó là dấu hiệu bạn làm đúng!",
         examples=[("man", "/mæn/", "người đàn ông"), ("mother", "/ˈmʌð.ər/", "mẹ"), ("same", "/seɪm/", "giống nhau"), ("summer", "/ˈsʌm.ər/", "mùa hè")],
         pair=("n", ["sum", "sun"])),
    dict(symbol="n", group="nasal_approx", category_vi="Phụ âm mũi", category_en="Nasal",
         description_vi="Đầu lưỡi chạm nướu trên, hơi thoát qua mũi",
         lips_vi="Hé mở", tongue_vi="Đầu lưỡi chạm nướu trên",
         articulation_vi="Đặt đầu lưỡi vào nướu trên, dây thanh rung, hơi thoát qua mũi. Cuối từ nhớ giữ lưỡi chạm nướu ('ten' ≠ 'te').",
         tip_vi="Khác 'ng': 'n' dùng ĐẦU lưỡi, 'ng' dùng CUỐNG lưỡi.",
         examples=[("no", "/nəʊ/", "không"), ("name", "/neɪm/", "tên"), ("ten", "/ten/", "số mười"), ("dinner", "/ˈdɪn.ər/", "bữa tối")],
         pair=("ŋ", ["sin", "sing"])),
    dict(symbol="ŋ", group="nasal_approx", category_vi="Phụ âm mũi", category_en="Nasal",
         description_vi="Cuống lưỡi chạm vòm mềm, hơi thoát qua mũi",
         lips_vi="Mở tự nhiên", tongue_vi="Cuống lưỡi nâng chạm vòm mềm",
         articulation_vi="Nâng phần sau lưỡi chạm vòm mềm như /k/ nhưng hơi thoát ra qua mũi, dây thanh rung. Không bật 'g' ở cuối ('sing' không phải 'sing-g').",
         tip_vi="Đúng như 'ng' tiếng Việt trong 'ngang' — nhưng chỉ đứng cuối/giữa từ.",
         examples=[("sing", "/sɪŋ/", "hát"), ("long", "/lɒŋ/", "dài"), ("thing", "/θɪŋ/", "thứ"), ("morning", "/ˈmɔː.nɪŋ/", "buổi sáng")],
         pair=("n", ["sing", "sin"])),
    dict(symbol="l", group="nasal_approx", category_vi="Phụ âm bên", category_en="Lateral",
         description_vi="Đầu lưỡi chạm nướu, hơi thoát hai bên lưỡi",
         lips_vi="Hé mở", tongue_vi="Đầu lưỡi chạm nướu trên",
         articulation_vi="Đặt đầu lưỡi lên nướu trên, để hơi thoát ra hai bên lưỡi, dây thanh rung. Cuối từ ('ball', 'feel') lưỡi vẫn phải chạm nướu — 'dark l'.",
         tip_vi="Cuối từ đừng biến 'l' thành 'n' hay bỏ hẳn: 'feel' ≠ 'fee'.",
         examples=[("light", "/laɪt/", "ánh sáng"), ("love", "/lʌv/", "yêu"), ("ball", "/bɔːl/", "quả bóng"), ("yellow", "/ˈjel.əʊ/", "màu vàng")],
         pair=("r", ["light", "right"])),
    dict(symbol="r", group="nasal_approx", category_vi="Phụ âm tiếp cận", category_en="Approximant",
         description_vi="Đầu lưỡi cong lên nhưng không chạm vòm, môi hơi tròn",
         lips_vi="Hơi tròn", tongue_vi="Cong lên, không chạm",
         articulation_vi="Cong đầu lưỡi lên phía vòm miệng nhưng KHÔNG chạm, môi hơi tròn, dây thanh rung. Không rung lưỡi như 'r' tiếng Việt miền Trung.",
         tip_vi="Lưỡi lơ lửng, không chạm gì cả — 'red' bắt đầu bằng môi tròn nhẹ.",
         examples=[("red", "/red/", "màu đỏ"), ("rain", "/reɪn/", "mưa"), ("carry", "/ˈkær.i/", "mang"), ("sorry", "/ˈsɒr.i/", "xin lỗi")],
         pair=("l", ["right", "light"])),
    dict(symbol="w", group="nasal_approx", category_vi="Bán nguyên âm", category_en="Semi-vowel",
         description_vi="Môi chụm tròn rồi mở nhanh sang nguyên âm",
         lips_vi="Chụm tròn rồi mở", tongue_vi="Nâng sau",
         articulation_vi="Chụm tròn môi như /uː/ rồi lướt nhanh sang nguyên âm phía sau, dây thanh rung. Rất ngắn, chỉ là cú chuyển động môi.",
         tip_vi="Bắt đầu bằng hình môi 'u' rồi bung ra: 'we' = 'u-i' nói thật nhanh.",
         examples=[("we", "/wiː/", "chúng tôi"), ("water", "/ˈwɔː.tər/", "nước"), ("window", "/ˈwɪn.dəʊ/", "cửa sổ"), ("away", "/əˈweɪ/", "đi xa")],
         pair=("v", ["wine", "vine"])),
    dict(symbol="j", group="nasal_approx", category_vi="Bán nguyên âm", category_en="Semi-vowel",
         description_vi="Lưỡi nâng cao như /iː/ rồi lướt sang nguyên âm",
         lips_vi="Bè nhẹ", tongue_vi="Nâng cao phía trước",
         articulation_vi="Đặt lưỡi ở vị trí /iː/ rồi lướt nhanh sang nguyên âm tiếp theo, dây thanh rung. Rất ngắn, không kéo dài.",
         tip_vi="Giống 'd' giọng Nam trong 'dì' — 'yes' = 'i-es' nói liền.",
         examples=[("yes", "/jes/", "vâng"), ("you", "/juː/", "bạn"), ("year", "/jɪər/", "năm"), ("music", "/ˈmjuː.zɪk/", "âm nhạc")],
         pair=("dʒ", ["yet", "jet"])),
]
# fmt: on

ALL_SOUNDS = [dict(kind="vowel", **v) for v in VOWELS] + [
    dict(kind="consonant", **c) for c in CONSONANTS
]
