"""40 gốc từ (C40): 14 tiền tố · 14 gốc Latin/Hy Lạp · 12 hậu tố — nguồn seed cho `seed_roots`.

Mỗi mục: kind, text, meaning_vi, group (nhóm hiển thị, thứ tự = vị trí trong GROUPS), effect_vi,
mnemonic_vi (Mẹo từ Bé Long), samples [(word, base, meaning_vi, ipa)]. Thứ tự trong nhóm = `order`.
"""

# fmt: off
GROUPS = [
    ("prefix", "Phủ định & Đối nghịch"),
    ("prefix", "Vị trí & Thời gian"),
    ("prefix", "Số lượng & Mức độ"),
    ("root", "Hành động & Chuyển động"),
    ("root", "Nhận thức & Giao tiếp"),
    ("root", "Sự sống & Thiên nhiên"),
    ("suffix", "Tạo danh từ"),
    ("suffix", "Tạo tính từ & trạng từ"),
]

ROOTS = [
    # ---- Tiền tố: Phủ định & Đối nghịch (6)
    dict(kind="prefix", text="un-", meaning_vi="không / ngược lại", group="Phủ định & Đối nghịch",
         effect_vi="Biến đổi nghĩa sang đối lập tức thì",
         mnemonic_vi="Hơn 80% từ có un- là tính từ biểu thị sự đối lập!",
         samples=[("unhappy", "happy", "không vui vẻ", "/ʌnˈhæp.i/"), ("unable", "able", "không có khả năng", "/ʌnˈeɪ.bəl/"),
                  ("unexpected", "expected", "bất ngờ, không lường", "/ˌʌn.ɪkˈspek.tɪd/"), ("unlock", "lock", "mở khóa", "/ʌnˈlɒk/"),
                  ("unfair", "fair", "không công bằng", "/ʌnˈfeər/")]),
    dict(kind="prefix", text="dis-", meaning_vi="tách / mất", group="Phủ định & Đối nghịch",
         effect_vi="Phủ định hoặc đảo ngược hành động",
         mnemonic_vi="dis- hay đi với động từ: agree → disagree, appear → disappear.",
         samples=[("disagree", "agree", "không đồng ý", "/ˌdɪs.əˈɡriː/"), ("disappear", "appear", "biến mất", "/ˌdɪs.əˈpɪər/"),
                  ("dislike", "like", "không thích", "/dɪsˈlaɪk/"), ("disconnect", "connect", "ngắt kết nối", "/ˌdɪs.kəˈnekt/")]),
    dict(kind="prefix", text="im-/in-", meaning_vi="không / bất", group="Phủ định & Đối nghịch",
         effect_vi="Phủ định tính từ gốc Latin",
         mnemonic_vi="Trước m, p, b dùng im- (impossible); còn lại dùng in- (invisible).",
         samples=[("impossible", "possible", "không thể", "/ɪmˈpɒs.ə.bəl/"), ("impolite", "polite", "bất lịch sự", "/ˌɪm.pəˈlaɪt/"),
                  ("invisible", "visible", "vô hình", "/ɪnˈvɪz.ə.bəl/"), ("incorrect", "correct", "không chính xác", "/ˌɪn.kəˈrekt/")]),
    dict(kind="prefix", text="non-", meaning_vi="phi / không", group="Phủ định & Đối nghịch",
         effect_vi="Phủ định trung tính, không mang sắc thái xấu",
         mnemonic_vi="non- là 'không thuộc loại đó': nonstop = không dừng.",
         samples=[("nonstop", "stop", "không ngừng", "/ˌnɒnˈstɒp/"), ("nonsense", "sense", "vô nghĩa", "/ˈnɒn.səns/"),
                  ("nonprofit", "profit", "phi lợi nhuận", "/ˌnɒnˈprɒf.ɪt/"), ("nonfiction", "fiction", "phi hư cấu", "/ˌnɒnˈfɪk.ʃən/")]),
    dict(kind="prefix", text="mis-", meaning_vi="sai / nhầm", group="Phủ định & Đối nghịch",
         effect_vi="Làm sai, làm nhầm hành động gốc",
         mnemonic_vi="mis- = 'miss' — làm trượt mục tiêu: misunderstand = hiểu nhầm.",
         samples=[("misunderstand", "understand", "hiểu nhầm", "/ˌmɪs.ʌn.dəˈstænd/"), ("mistake", "take", "sai lầm", "/mɪˈsteɪk/"),
                  ("misspell", "spell", "viết sai chính tả", "/ˌmɪsˈspel/"), ("mislead", "lead", "dẫn dắt sai", "/ˌmɪsˈliːd/")]),
    dict(kind="prefix", text="anti-", meaning_vi="chống / đối", group="Phủ định & Đối nghịch",
         effect_vi="Đối kháng, chống lại điều gì",
         mnemonic_vi="anti- = chống: antivirus chống virus, antisocial chống xã giao.",
         samples=[("antivirus", "virus", "diệt virus", "/ˈæn.tiˌvaɪ.rəs/"), ("antisocial", "social", "chống đối xã hội", "/ˌæn.tiˈsəʊ.ʃəl/"),
                  ("antibiotic", "biotic", "kháng sinh", "/ˌæn.ti.baɪˈɒt.ɪk/"), ("anticlockwise", "clockwise", "ngược chiều kim đồng hồ", "/ˌæn.tiˈklɒk.waɪz/")]),
    # ---- Tiền tố: Vị trí & Thời gian (4)
    dict(kind="prefix", text="pre-", meaning_vi="trước", group="Vị trí & Thời gian",
         effect_vi="Xảy ra trước hành động gốc",
         mnemonic_vi="pre- = trước: preview xem trước, predict đoán trước.",
         samples=[("preview", "view", "xem trước", "/ˈpriː.vjuː/"), ("predict", "dict", "dự đoán", "/prɪˈdɪkt/"),
                  ("prepare", "pare", "chuẩn bị", "/prɪˈpeər/"), ("prehistoric", "historic", "tiền sử", "/ˌpriː.hɪˈstɒr.ɪk/")]),
    dict(kind="prefix", text="re-", meaning_vi="lại / trở lại", group="Vị trí & Thời gian",
         effect_vi="Lặp lại hoặc quay về",
         mnemonic_vi="re- = làm lại lần nữa: rewrite, replay, return.",
         samples=[("rewrite", "write", "viết lại", "/ˌriːˈraɪt/"), ("replay", "play", "phát lại", "/ˌriːˈpleɪ/"),
                  ("return", "turn", "quay lại", "/rɪˈtɜːn/"), ("rebuild", "build", "xây lại", "/ˌriːˈbɪld/")]),
    dict(kind="prefix", text="sub-", meaning_vi="dưới / phụ", group="Vị trí & Thời gian",
         effect_vi="Ở bên dưới hoặc cấp thấp hơn",
         mnemonic_vi="sub- = dưới: subway đường ngầm, subtitle phụ đề (dưới hình).",
         samples=[("subway", "way", "tàu điện ngầm", "/ˈsʌb.weɪ/"), ("subtitle", "title", "phụ đề", "/ˈsʌbˌtaɪ.təl/"),
                  ("submarine", "marine", "tàu ngầm", "/ˌsʌb.məˈriːn/"), ("subtopic", "topic", "chủ đề phụ", "/ˈsʌbˌtɒp.ɪk/")]),
    dict(kind="prefix", text="inter-", meaning_vi="giữa / lẫn nhau", group="Vị trí & Thời gian",
         effect_vi="Kết nối giữa hai bên",
         mnemonic_vi="inter- = giữa các: international giữa các quốc gia, internet mạng liên kết.",
         samples=[("international", "national", "quốc tế", "/ˌɪn.təˈnæʃ.ən.əl/"), ("interact", "act", "tương tác", "/ˌɪn.təˈrækt/"),
                  ("interview", "view", "phỏng vấn", "/ˈɪn.tə.vjuː/"), ("interchange", "change", "trao đổi", "/ˈɪn.tə.tʃeɪndʒ/")]),
    # ---- Tiền tố: Số lượng & Mức độ (4)
    dict(kind="prefix", text="over-", meaning_vi="quá / vượt", group="Số lượng & Mức độ",
         effect_vi="Quá mức cần thiết",
         mnemonic_vi="over- = quá đà: oversleep ngủ quên, overeat ăn quá nhiều.",
         samples=[("oversleep", "sleep", "ngủ quên", "/ˌəʊ.vəˈsliːp/"), ("overeat", "eat", "ăn quá nhiều", "/ˌəʊ.vəˈiːt/"),
                  ("overload", "load", "quá tải", "/ˌəʊ.vəˈləʊd/"), ("overpriced", "priced", "giá quá cao", "/ˌəʊ.vəˈpraɪst/")]),
    dict(kind="prefix", text="under-", meaning_vi="thiếu / dưới", group="Số lượng & Mức độ",
         effect_vi="Chưa đủ mức hoặc ở dưới",
         mnemonic_vi="under- ngược với over-: underpaid trả lương thấp, underground dưới đất.",
         samples=[("underpaid", "paid", "trả lương thấp", "/ˌʌn.dəˈpeɪd/"), ("underground", "ground", "dưới lòng đất", "/ˌʌn.dəˈɡraʊnd/"),
                  ("underestimate", "estimate", "đánh giá thấp", "/ˌʌn.dəˈres.tɪ.meɪt/"), ("undercooked", "cooked", "chưa chín", "/ˌʌn.dəˈkʊkt/")]),
    dict(kind="prefix", text="super-", meaning_vi="siêu / vượt trội", group="Số lượng & Mức độ",
         effect_vi="Vượt trên mức bình thường",
         mnemonic_vi="super- = siêu: superhero, supermarket (siêu thị).",
         samples=[("superhero", "hero", "siêu anh hùng", "/ˈsuː.pəˌhɪə.rəʊ/"), ("supermarket", "market", "siêu thị", "/ˈsuː.pəˌmɑː.kɪt/"),
                  ("superstar", "star", "siêu sao", "/ˈsuː.pə.stɑːr/"), ("supernatural", "natural", "siêu nhiên", "/ˌsuː.pəˈnætʃ.ər.əl/")]),
    dict(kind="prefix", text="semi-", meaning_vi="nửa / bán", group="Số lượng & Mức độ",
         effect_vi="Một nửa hoặc một phần",
         mnemonic_vi="semi- = một nửa: semifinal bán kết, semicircle nửa vòng tròn.",
         samples=[("semifinal", "final", "bán kết", "/ˌsem.iˈfaɪ.nəl/"), ("semicircle", "circle", "nửa vòng tròn", "/ˈsem.iˌsɜː.kəl/"),
                  ("semiautomatic", "automatic", "bán tự động", "/ˌsem.iˌɔː.təˈmæt.ɪk/"), ("semidetached", "detached", "nhà liền kề một bên", "/ˌsem.i.dɪˈtætʃt/")]),

    # ---- Gốc: Hành động & Chuyển động (5)
    dict(kind="root", text="port", meaning_vi="mang / chở", group="Hành động & Chuyển động",
         effect_vi="Từ chứa port đều liên quan đến vận chuyển",
         mnemonic_vi="port = cảng — nơi hàng được mang đi: transport, import, export.",
         samples=[("transport", "trans", "vận chuyển", "/ˈtræn.spɔːt/"), ("import", "im", "nhập khẩu", "/ˈɪm.pɔːt/"),
                  ("export", "ex", "xuất khẩu", "/ˈek.spɔːt/"), ("portable", "able", "xách tay được", "/ˈpɔː.tə.bəl/")]),
    dict(kind="root", text="duct/duc", meaning_vi="dẫn / đưa", group="Hành động & Chuyển động",
         effect_vi="Dẫn dắt, đưa đến",
         mnemonic_vi="duct = ống dẫn: conduct dẫn dắt, produce đưa ra sản phẩm.",
         samples=[("conduct", "con", "dẫn dắt, chỉ huy", "/kənˈdʌkt/"), ("produce", "pro", "sản xuất", "/prəˈdjuːs/"),
                  ("introduce", "intro", "giới thiệu", "/ˌɪn.trəˈdjuːs/"), ("reduce", "re", "giảm bớt", "/rɪˈdjuːs/")]),
    dict(kind="root", text="mit/miss", meaning_vi="gửi / thả", group="Hành động & Chuyển động",
         effect_vi="Gửi đi, cho phép đi",
         mnemonic_vi="mission = nhiệm vụ được 'gửi' đi; submit = gửi (xuống) bài.",
         samples=[("submit", "sub", "nộp, gửi", "/səbˈmɪt/"), ("permit", "per", "cho phép", "/pəˈmɪt/"),
                  ("mission", "ion", "nhiệm vụ", "/ˈmɪʃ.ən/"), ("transmit", "trans", "truyền đi", "/trænzˈmɪt/")]),
    dict(kind="root", text="ject", meaning_vi="ném / phóng", group="Hành động & Chuyển động",
         effect_vi="Ném về một hướng",
         mnemonic_vi="ject = ném: reject ném trả lại, project ném ra phía trước (kế hoạch).",
         samples=[("reject", "re", "từ chối", "/rɪˈdʒekt/"), ("project", "pro", "dự án", "/ˈprɒdʒ.ekt/"),
                  ("inject", "in", "tiêm", "/ɪnˈdʒekt/"), ("object", "ob", "đồ vật; phản đối", "/ˈɒb.dʒɪkt/")]),
    dict(kind="root", text="struct", meaning_vi="xây / dựng", group="Hành động & Chuyển động",
         effect_vi="Xây dựng, sắp xếp",
         mnemonic_vi="struct = xây: construct xây dựng, structure cấu trúc, instruct 'xây' kiến thức.",
         samples=[("construct", "con", "xây dựng", "/kənˈstrʌkt/"), ("structure", "ure", "cấu trúc", "/ˈstrʌk.tʃər/"),
                  ("instruct", "in", "hướng dẫn", "/ɪnˈstrʌkt/"), ("destruction", "de", "sự phá hủy", "/dɪˈstrʌk.ʃən/")]),
    # ---- Gốc: Nhận thức & Giao tiếp (5)
    dict(kind="root", text="dict", meaning_vi="nói", group="Nhận thức & Giao tiếp",
         effect_vi="Liên quan đến lời nói, tuyên bố",
         mnemonic_vi="dict = nói: dictionary sách 'nói' nghĩa, predict nói trước.",
         samples=[("dictionary", "ionary", "từ điển", "/ˈdɪk.ʃən.ər.i/"), ("predict", "pre", "dự đoán", "/prɪˈdɪkt/"),
                  ("contradict", "contra", "mâu thuẫn", "/ˌkɒn.trəˈdɪkt/"), ("verdict", "ver", "phán quyết", "/ˈvɜː.dɪkt/")]),
    dict(kind="root", text="scrib/script", meaning_vi="viết", group="Nhận thức & Giao tiếp",
         effect_vi="Liên quan đến viết, ghi chép",
         mnemonic_vi="script = kịch bản (được viết ra); describe = viết mô tả.",
         samples=[("describe", "de", "mô tả", "/dɪˈskraɪb/"), ("subscribe", "sub", "đăng ký theo dõi", "/səbˈskraɪb/"),
                  ("manuscript", "manu", "bản thảo", "/ˈmæn.jə.skrɪpt/"), ("prescription", "pre", "đơn thuốc", "/prɪˈskrɪp.ʃən/")]),
    dict(kind="root", text="spect", meaning_vi="nhìn", group="Nhận thức & Giao tiếp",
         effect_vi="Nhìn, quan sát",
         mnemonic_vi="spect = nhìn: inspect nhìn kỹ, respect nhìn lại (kính trọng), spectator người xem.",
         samples=[("inspect", "in", "kiểm tra", "/ɪnˈspekt/"), ("respect", "re", "tôn trọng", "/rɪˈspekt/"),
                  ("spectator", "ator", "khán giả", "/spekˈteɪ.tər/"), ("perspective", "per", "góc nhìn", "/pəˈspek.tɪv/")]),
    dict(kind="root", text="aud", meaning_vi="nghe", group="Nhận thức & Giao tiếp",
         effect_vi="Liên quan đến âm thanh, nghe",
         mnemonic_vi="aud = nghe: audio, audience (người nghe), audible (nghe được).",
         samples=[("audio", "io", "âm thanh", "/ˈɔː.di.əʊ/"), ("audience", "ience", "khán giả", "/ˈɔː.di.əns/"),
                  ("audible", "ible", "nghe được", "/ˈɔː.də.bəl/"), ("audition", "ition", "buổi thử giọng", "/ɔːˈdɪʃ.ən/")]),
    dict(kind="root", text="graph/gram", meaning_vi="viết / vẽ", group="Nhận thức & Giao tiếp",
         effect_vi="Ghi lại bằng chữ hoặc hình",
         mnemonic_vi="graph = vẽ/ghi: photograph ghi bằng ánh sáng, autograph tự viết (chữ ký).",
         samples=[("photograph", "photo", "bức ảnh", "/ˈfəʊ.tə.ɡrɑːf/"), ("autograph", "auto", "chữ ký", "/ˈɔː.tə.ɡrɑːf/"),
                  ("paragraph", "para", "đoạn văn", "/ˈpær.ə.ɡrɑːf/"), ("grammar", "mar", "ngữ pháp", "/ˈɡræm.ər/")]),
    # ---- Gốc: Sự sống & Thiên nhiên (4)
    dict(kind="root", text="bio", meaning_vi="sự sống", group="Sự sống & Thiên nhiên",
         effect_vi="Liên quan đến sinh học, sự sống",
         mnemonic_vi="bio = sống: biology, biography (viết về cuộc đời).",
         samples=[("biology", "logy", "sinh học", "/baɪˈɒl.ə.dʒi/"), ("biography", "graphy", "tiểu sử", "/baɪˈɒɡ.rə.fi/"),
                  ("antibiotic", "antitic", "kháng sinh", "/ˌæn.ti.baɪˈɒt.ɪk/"), ("biodiversity", "diversity", "đa dạng sinh học", "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/")]),
    dict(kind="root", text="geo", meaning_vi="trái đất", group="Sự sống & Thiên nhiên",
         effect_vi="Liên quan đến đất, địa lý",
         mnemonic_vi="geo = đất: geography vẽ bản đồ đất, geology học về đất đá.",
         samples=[("geography", "graphy", "địa lý", "/dʒiˈɒɡ.rə.fi/"), ("geology", "logy", "địa chất học", "/dʒiˈɒl.ə.dʒi/"),
                  ("geometry", "metry", "hình học", "/dʒiˈɒm.ə.tri/"), ("geothermal", "thermal", "địa nhiệt", "/ˌdʒiː.əʊˈθɜː.məl/")]),
    dict(kind="root", text="aqua/hydr", meaning_vi="nước", group="Sự sống & Thiên nhiên",
         effect_vi="Liên quan đến nước",
         mnemonic_vi="aqua (Latin) và hydr (Hy Lạp) đều là nước: aquarium bể cá, hydrate cấp nước.",
         samples=[("aquarium", "rium", "bể cá", "/əˈkweə.ri.əm/"), ("aquatic", "tic", "thuộc về nước", "/əˈkwæt.ɪk/"),
                  ("hydrate", "ate", "cấp nước", "/haɪˈdreɪt/"), ("hydrogen", "ogen", "khí hydro", "/ˈhaɪ.drə.dʒən/")]),
    dict(kind="root", text="chron", meaning_vi="thời gian", group="Sự sống & Thiên nhiên",
         effect_vi="Liên quan đến thời gian, trình tự",
         mnemonic_vi="chron = thời gian: chronic (kéo dài), synchronize (cùng thời điểm).",
         samples=[("chronic", "ic", "mãn tính", "/ˈkrɒn.ɪk/"), ("synchronize", "syn", "đồng bộ", "/ˈsɪŋ.krə.naɪz/"),
                  ("chronology", "ology", "niên đại", "/krəˈnɒl.ə.dʒi/"), ("chronicle", "icle", "biên niên sử", "/ˈkrɒn.ɪ.kəl/")]),

    # ---- Hậu tố: Tạo danh từ (6)
    dict(kind="suffix", text="-er/-or", meaning_vi="người / vật làm", group="Tạo danh từ",
         effect_vi="Động từ → người/vật thực hiện hành động",
         mnemonic_vi="teach → teacher, act → actor: thêm -er/-or là ra 'người làm'.",
         samples=[("teacher", "teach", "giáo viên", "/ˈtiː.tʃər/"), ("driver", "drive", "tài xế", "/ˈdraɪ.vər/"),
                  ("actor", "act", "diễn viên", "/ˈæk.tər/"), ("visitor", "visit", "khách thăm", "/ˈvɪz.ɪ.tər/")]),
    dict(kind="suffix", text="-tion/-sion", meaning_vi="hành động / trạng thái", group="Tạo danh từ",
         effect_vi="Động từ → danh từ chỉ hành động",
         mnemonic_vi="Hậu tố danh từ phổ biến nhất: educate → education, decide → decision.",
         samples=[("education", "educa", "giáo dục", "/ˌedʒ.uˈkeɪ.ʃən/"), ("information", "informa", "thông tin", "/ˌɪn.fəˈmeɪ.ʃən/"),
                  ("decision", "deci", "quyết định", "/dɪˈsɪʒ.ən/"), ("celebration", "celebra", "lễ kỷ niệm", "/ˌsel.əˈbreɪ.ʃən/")]),
    dict(kind="suffix", text="-ment", meaning_vi="kết quả / quá trình", group="Tạo danh từ",
         effect_vi="Động từ → danh từ chỉ kết quả",
         mnemonic_vi="-ment 'đóng gói' hành động thành danh từ: develop → development.",
         samples=[("development", "develop", "sự phát triển", "/dɪˈvel.əp.mənt/"), ("movement", "move", "chuyển động", "/ˈmuːv.mənt/"),
                  ("agreement", "agree", "thỏa thuận", "/əˈɡriː.mənt/"), ("equipment", "equip", "thiết bị", "/ɪˈkwɪp.mənt/")]),
    dict(kind="suffix", text="-ness", meaning_vi="tính chất / trạng thái", group="Tạo danh từ",
         effect_vi="Tính từ → danh từ trừu tượng",
         mnemonic_vi="happy → happiness: -ness biến tính từ thành 'sự…'.",
         samples=[("happiness", "happi", "hạnh phúc", "/ˈhæp.i.nəs/"), ("kindness", "kind", "lòng tốt", "/ˈkaɪnd.nəs/"),
                  ("darkness", "dark", "bóng tối", "/ˈdɑːk.nəs/"), ("weakness", "weak", "điểm yếu", "/ˈwiːk.nəs/")]),
    dict(kind="suffix", text="-ity", meaning_vi="tính chất", group="Tạo danh từ",
         effect_vi="Tính từ Latin → danh từ",
         mnemonic_vi="able → ability, real → reality: -ity đi với tính từ gốc Latin.",
         samples=[("ability", "abil", "khả năng", "/əˈbɪl.ə.ti/"), ("reality", "real", "thực tế", "/riˈæl.ə.ti/"),
                  ("activity", "activ", "hoạt động", "/ækˈtɪv.ə.ti/"), ("possibility", "possibil", "khả năng xảy ra", "/ˌpɒs.əˈbɪl.ə.ti/")]),
    dict(kind="suffix", text="-ship/-hood", meaning_vi="mối quan hệ / địa vị", group="Tạo danh từ",
         effect_vi="Danh từ → danh từ chỉ quan hệ, trạng thái",
         mnemonic_vi="friend → friendship, child → childhood: quan hệ và giai đoạn.",
         samples=[("friendship", "friend", "tình bạn", "/ˈfrend.ʃɪp/"), ("leadership", "leader", "sự lãnh đạo", "/ˈliː.də.ʃɪp/"),
                  ("childhood", "child", "tuổi thơ", "/ˈtʃaɪld.hʊd/"), ("neighborhood", "neighbor", "khu dân cư", "/ˈneɪ.bə.hʊd/")]),
    # ---- Hậu tố: Tạo tính từ & trạng từ (6)
    dict(kind="suffix", text="-ful", meaning_vi="đầy / có nhiều", group="Tạo tính từ & trạng từ",
         effect_vi="Danh từ → tính từ 'đầy…'",
         mnemonic_vi="-ful = full: careful đầy cẩn thận, beautiful đầy vẻ đẹp.",
         samples=[("careful", "care", "cẩn thận", "/ˈkeə.fəl/"), ("beautiful", "beauti", "xinh đẹp", "/ˈbjuː.tɪ.fəl/"),
                  ("helpful", "help", "hữu ích", "/ˈhelp.fəl/"), ("powerful", "power", "mạnh mẽ", "/ˈpaʊə.fəl/")]),
    dict(kind="suffix", text="-less", meaning_vi="không có", group="Tạo tính từ & trạng từ",
         effect_vi="Danh từ → tính từ 'thiếu…'",
         mnemonic_vi="-less ngược với -ful: careful ↔ careless, hopeful ↔ hopeless.",
         samples=[("careless", "care", "bất cẩn", "/ˈkeə.ləs/"), ("hopeless", "hope", "vô vọng", "/ˈhəʊp.ləs/"),
                  ("useless", "use", "vô dụng", "/ˈjuːs.ləs/"), ("wireless", "wire", "không dây", "/ˈwaɪə.ləs/")]),
    dict(kind="suffix", text="-able/-ible", meaning_vi="có thể", group="Tạo tính từ & trạng từ",
         effect_vi="Động từ → tính từ 'có thể được…'",
         mnemonic_vi="-able = able: readable đọc được, flexible uốn được.",
         samples=[("readable", "read", "dễ đọc", "/ˈriː.də.bəl/"), ("comfortable", "comfort", "thoải mái", "/ˈkʌm.fə.tə.bəl/"),
                  ("flexible", "flex", "linh hoạt", "/ˈflek.sə.bəl/"), ("visible", "vis", "nhìn thấy được", "/ˈvɪz.ə.bəl/")]),
    dict(kind="suffix", text="-ous", meaning_vi="có tính chất", group="Tạo tính từ & trạng từ",
         effect_vi="Danh từ → tính từ",
         mnemonic_vi="danger → dangerous, fame → famous: -ous = 'đầy tính…'.",
         samples=[("dangerous", "danger", "nguy hiểm", "/ˈdeɪn.dʒər.əs/"), ("famous", "fam", "nổi tiếng", "/ˈfeɪ.məs/"),
                  ("nervous", "nerv", "lo lắng", "/ˈnɜː.vəs/"), ("delicious", "delici", "ngon", "/dɪˈlɪʃ.əs/")]),
    dict(kind="suffix", text="-al/-ic", meaning_vi="thuộc về", group="Tạo tính từ & trạng từ",
         effect_vi="Danh từ → tính từ 'thuộc về…'",
         mnemonic_vi="nation → national, history → historic: 'thuộc về' danh từ gốc.",
         samples=[("national", "nation", "thuộc quốc gia", "/ˈnæʃ.ən.əl/"), ("natural", "natur", "tự nhiên", "/ˈnætʃ.ər.əl/"),
                  ("historic", "histor", "mang tính lịch sử", "/hɪˈstɒr.ɪk/"), ("economic", "econom", "thuộc kinh tế", "/ˌiː.kəˈnɒm.ɪk/")]),
    dict(kind="suffix", text="-ly", meaning_vi="một cách", group="Tạo tính từ & trạng từ",
         effect_vi="Tính từ → trạng từ",
         mnemonic_vi="quick → quickly: thêm -ly là có trạng từ chỉ cách thức.",
         samples=[("quickly", "quick", "một cách nhanh chóng", "/ˈkwɪk.li/"), ("happily", "happi", "một cách vui vẻ", "/ˈhæp.ɪ.li/"),
                  ("carefully", "careful", "một cách cẩn thận", "/ˈkeə.fəl.i/"), ("finally", "final", "cuối cùng", "/ˈfaɪ.nəl.i/")]),
]
# fmt: on
