# Generated by Django 5.1.15 on 2026-09-03 13:51

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('avatar_path', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('family_id', models.UUIDField(default=uuid.uuid4)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], max_length=16)),
                ('provider_uid', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_accounts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 — Mới bắt đầu'), ('A2', 'A2 — Sơ cấp'), ('B1', 'B1 — Trung cấp'), ('B2', 'B2 — Trung cao'), ('C1', 'C1 — Cao cấp'), ('C2', 'C2 — Thành thạo')], default='A1', max_length=2)),
                ('goal_level', models.CharField(choices=[('A1', 'A1 — Mới bắt đầu'), ('A2', 'A2 — Sơ cấp'), ('B1', 'B1 — Trung cấp'), ('B2', 'B2 — Trung cao'), ('C1', 'C1 — Cao cấp'), ('C2', 'C2 — Thành thạo')], default='B1', max_length=2)),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('hearts', models.PositiveSmallIntegerField(default=5)),
                ('hearts_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('streak_current', models.PositiveIntegerField(default=0)),
                ('streak_best', models.PositiveIntegerField(default=0)),
                ('streak_freezes', models.PositiveSmallIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('accent', models.CharField(choices=[('UK', 'Anh-Anh'), ('US', 'Anh-Mỹ')], default='US', max_length=2)),
                ('show_ipa', models.BooleanField(default=True)),
                ('daily_goal_xp', models.PositiveSmallIntegerField(default=50)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=40)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['last_active_date'], name='profile_lastactive_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted_at__isnull', False)), fields=['deleted_at'], name='user_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'revoked_at'], name='rt_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['family_id'], name='rt_family_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='rt_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_uid'), name='uniq_social_provider_uid'),
        ),
    ]
