# Generated by Django 5.1.15 on 2026-09-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal_words',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
