# Generated by Django 5.1.15 on 2026-09-04 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_daily_goal_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='event_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ui_language',
            field=models.CharField(default='vi', max_length=5),
        ),
    ]
