# Generated by Django 5.1.15 on 2026-09-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_event_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learning_goal',
            field=models.CharField(choices=[('daily', 'Giao tiếp hàng ngày'), ('ielts', 'Du học / IELTS'), ('toeic', 'Công việc / TOEIC'), ('travel', 'Du lịch khám phá'), ('media', 'Phim ảnh & Nhạc'), ('kids', 'Cho con / Học sinh')], default='daily', max_length=12),
        ),
    ]
