# Generated by Django 5.1.15 on 2026-09-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_frame',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_lost_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp_boost_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
