# Generated by Django 5.1.15 on 2026-09-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_avatar_frame_userprofile_streak_lost_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='streak_frozen_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
