# Generated by Django 5.1.15 on 2026-09-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_streak_frozen_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plus_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
