# Generated by Django 5.1.15 on 2026-09-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('name_vi', models.CharField(max_length=64)),
                ('period', models.CharField(choices=[('month', 'Tháng'), ('year', 'Năm'), ('lifetime', 'Trọn đời')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('original_price', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('badge_vi', models.CharField(blank=True, max_length=32)),
                ('features', models.JSONField(default=list)),
                ('store_ids', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
