# Generated by Django 5.1.15 on 2026-09-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('premium', 'Gói Premium'), ('coins', 'Gói xu')], default='premium', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='period',
            field=models.CharField(choices=[('month', 'Tháng'), ('year', 'Năm'), ('lifetime', 'Trọn đời'), ('one_time', 'Mua 1 lần')], max_length=10),
        ),
    ]
