# Generated by Django 5.1.15 on 2026-09-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_product_coins_product_kind_alter_product_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tier',
            field=models.CharField(choices=[('premium', 'Premium'), ('plus', 'Premium+')], default='premium', max_length=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='will_renew',
            field=models.BooleanField(default=False),
        ),
    ]
