# Generated by Django 5.1.15 on 2026-09-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_premium_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="period",
            field=models.CharField(
                choices=[
                    ("month", "Tháng"),
                    ("quarter", "3 tháng"),
                    ("year", "Năm"),
                    ("lifetime", "Trọn đời"),
                    ("one_time", "Mua 1 lần"),
                ],
                max_length=10,
            ),
        ),
    ]
