# Generated by Django 5.1.15 on 2026-09-04 01:41

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_extensions"),   # pg_trgm phải có trước GinIndex
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=128)),
                ('title_vi', models.CharField(blank=True, max_length=128)),
                ('context_vi', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('category', models.CharField(blank=True, max_length=48)),
                ('title_vi', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('formula', models.CharField(blank=True, max_length=160)),
                ('explanation_vi', models.TextField()),
                ('common_mistake_vi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPASound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8, unique=True)),
                ('kind', models.CharField(choices=[('vowel', 'Nguyên âm'), ('consonant', 'Phụ âm')], max_length=10)),
                ('description_vi', models.CharField(max_length=255)),
                ('mouth_image_path', models.CharField(blank=True, max_length=255)),
                ('sample_words', models.JSONField(default=list)),
                ('minimal_pair', models.JSONField(blank=True, default=dict)),
                ('audio_uk_path', models.CharField(blank=True, max_length=255)),
                ('audio_us_path', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('title_vi', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128)),
                ('description_vi', models.TextField(blank=True)),
                ('est_minutes', models.PositiveSmallIntegerField(default=12)),
                ('xp_reward', models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('code', models.CharField(choices=[('A1', 'A1 — Mới bắt đầu'), ('A2', 'A2 — Sơ cấp'), ('B1', 'B1 — Trung cấp'), ('B2', 'B2 — Trung cao'), ('C1', 'C1 — Cao cấp'), ('C2', 'C2 — Thành thạo')], max_length=2, primary_key=True, serialize=False)),
                ('name_vi', models.CharField(max_length=64)),
                ('description_vi', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('word_target', models.PositiveIntegerField(default=600)),
                ('is_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('name_vi', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('icon', models.CharField(blank=True, max_length=48)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DialogueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('speaker', models.CharField(max_length=32)),
                ('text_en', models.CharField(max_length=255)),
                ('text_vi', models.CharField(max_length=255)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='content.dialogue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text_en', models.CharField(max_length=255)),
                ('text_vi', models.CharField(max_length=255)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('grammar_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='content.grammarpoint')),
            ],
        ),
        migrations.AddField(
            model_name='dialogue',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grammar_points', to='content.level'),
        ),
        migrations.CreateModel(
            name='PhrasalVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_group', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=48, unique=True)),
                ('ipa', models.CharField(blank=True, max_length=64)),
                ('meaning_vi', models.CharField(max_length=160)),
                ('explanation_vi', models.TextField(blank=True)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phrasal_verbs', to='content.level')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title_en', models.CharField(max_length=128)),
                ('title_vi', models.CharField(max_length=128)),
                ('est_minutes', models.PositiveSmallIntegerField(default=2)),
                ('cover_path', models.CharField(blank=True, max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='content.level')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('question_en', models.CharField(max_length=512)),
                ('options', models.JSONField()),
                ('answer_index', models.PositiveSmallIntegerField()),
                ('explanation_vi', models.CharField(blank=True, max_length=512)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.reading')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text_en', models.CharField(max_length=512)),
                ('text_vi', models.CharField(max_length=512)),
                ('ipa', models.CharField(blank=True, max_length=512)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='content.reading')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title_en', models.CharField(max_length=128)),
                ('title_vi', models.CharField(max_length=128)),
                ('genre', models.CharField(blank=True, max_length=48)),
                ('synopsis_vi', models.CharField(blank=True, max_length=512)),
                ('cover_path', models.CharField(blank=True, max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='content.level')),
            ],
        ),
        migrations.CreateModel(
            name='StoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('question_en', models.CharField(max_length=512)),
                ('options', models.JSONField()),
                ('answer_index', models.PositiveSmallIntegerField()),
                ('explanation_vi', models.CharField(blank=True, max_length=512)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('illustration_path', models.CharField(blank=True, max_length=255)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='content.story')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StorySentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text_en', models.CharField(max_length=512)),
                ('text_vi', models.CharField(max_length=512)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='content.storyscene')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('code', models.SlugField(max_length=64)),
                ('title_vi', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128)),
                ('description_vi', models.CharField(blank=True, max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='content.level')),
            ],
            options={
                'ordering': ['level__order', 'order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.unit'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=24, unique=True)),
                ('title_vi', models.CharField(max_length=160)),
                ('title_en', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=48)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('thumbnail_path', models.CharField(blank=True, max_length=255)),
                ('is_free', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='content.level')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('text_en', models.CharField(max_length=512)),
                ('ipa', models.CharField(blank=True, max_length=512)),
                ('text_vi', models.CharField(max_length=512)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='content.video')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headword', models.CharField(max_length=64)),
                ('pos', models.CharField(choices=[('n', 'Danh từ'), ('v', 'Động từ'), ('adj', 'Tính từ'), ('adv', 'Trạng từ'), ('prep', 'Giới từ'), ('pron', 'Đại từ'), ('conj', 'Liên từ'), ('det', 'Từ hạn định'), ('excl', 'Thán từ')], max_length=6)),
                ('meaning_vi', models.CharField(max_length=255)),
                ('definition_en', models.TextField(blank=True)),
                ('ipa_uk', models.CharField(blank=True, max_length=64)),
                ('ipa_us', models.CharField(blank=True, max_length=64)),
                ('syllables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None)),
                ('ipa_syllables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None)),
                ('primary_stress', models.SmallIntegerField(blank=True, null=True)),
                ('secondary_stress', models.SmallIntegerField(blank=True, null=True)),
                ('audio_uk_path', models.CharField(blank=True, max_length=255)),
                ('audio_us_path', models.CharField(blank=True, max_length=255)),
                ('frequency_rank', models.IntegerField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary', to='content.level')),
                ('topics', models.ManyToManyField(blank=True, related_name='vocabulary', to='content.topic')),
                ('word_family', models.ManyToManyField(blank=True, to='content.vocabulary')),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='readings', to='content.vocabulary'),
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('intro', 'Giới thiệu'), ('vocab', 'Từ vựng'), ('grammar', 'Ngữ pháp'), ('dialogue', 'Hội thoại'), ('spelling', 'Luyện viết'), ('quiz', 'Luyện tập')], max_length=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dialogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.dialogue')),
                ('grammar_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.grammarpoint')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content.lesson')),
                ('vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.vocabulary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=128)),
                ('meaning_vi', models.CharField(blank=True, max_length=128)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collocations', to='content.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text_en', models.CharField(max_length=255)),
                ('text_vi', models.CharField(max_length=255)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='content.vocabulary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WordRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('prefix', 'Tiền tố'), ('root', 'Gốc từ'), ('suffix', 'Hậu tố')], max_length=8)),
                ('text', models.CharField(max_length=32)),
                ('meaning_vi', models.CharField(max_length=128)),
                ('group_vi', models.CharField(blank=True, max_length=64)),
                ('mnemonic_vi', models.TextField(blank=True)),
                ('examples', models.ManyToManyField(blank=True, related_name='roots', to='content.vocabulary')),
            ],
        ),
        migrations.AddConstraint(
            model_name='grammarpoint',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='uniq_grammar_order'),
        ),
        migrations.AddIndex(
            model_name='phrasalverb',
            index=models.Index(fields=['verb_group'], name='pv_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='uniq_story_order'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='uniq_unit_order'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='uniq_lesson_order'),
        ),
        migrations.AddIndex(
            model_name='videosubtitle',
            index=models.Index(fields=['video', 'start_ms'], name='sub_video_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['level', 'frequency_rank'], name='vocab_level_freq_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['headword'], name='vocab_headword_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(fields=('headword', 'pos'), name='uniq_headword_pos'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='uniq_reading_order'),
        ),
        migrations.AddIndex(
            model_name='lessonstep',
            index=models.Index(fields=['lesson', 'kind'], name='step_lesson_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonstep',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='uniq_step_order'),
        ),
        migrations.AddConstraint(
            model_name='wordroot',
            constraint=models.UniqueConstraint(fields=('kind', 'text'), name='uniq_root'),
        ),
    ]
