# Generated by Django 5.1.15 on 2026-09-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogueline',
            name='ipa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dialogueline',
            name='is_native',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grammarexample',
            name='ipa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='conjugation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lessonstep',
            name='kind',
            field=models.CharField(choices=[('intro', 'Giới thiệu'), ('vocab', 'Từ vựng'), ('grammar', 'Ngữ pháp'), ('dialogue', 'Hội thoại'), ('spelling', 'Luyện viết'), ('quiz', 'Luyện tập'), ('writing', 'Viết câu (AI)')], max_length=12),
        ),
    ]
