# Generated by Django 5.1.15 on 2026-09-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_dialogueline_ipa_dialogueline_is_native_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipasound',
            name='articulation_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='reward',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='synonyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ShadowingDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title_en', models.CharField(max_length=128)),
                ('title_vi', models.CharField(blank=True, max_length=128)),
                ('focus_vi', models.CharField(blank=True, max_length=128)),
                ('est_seconds', models.PositiveIntegerField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shadowing_decks', to='content.level')),
            ],
        ),
        migrations.CreateModel(
            name='ShadowingSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text_en', models.CharField(max_length=512)),
                ('ipa', models.CharField(blank=True, max_length=512)),
                ('text_vi', models.CharField(max_length=512)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='content.shadowingdeck')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='shadowingdeck',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='uniq_shadowing_order'),
        ),
    ]
