# Generated by Django 5.1.15 on 2026-09-04 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_ipasound_articulation_vi_unit_reward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('url', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField(default=0)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bundle', to='content.level')),
            ],
        ),
    ]
