# Generated by Django 5.1.15 on 2026-09-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contentbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='subtitle',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='LevelMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('code', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('title_vi', models.CharField(max_length=128)),
                ('requirement_lessons', models.PositiveSmallIntegerField()),
                ('reward_xp', models.PositiveSmallIntegerField(default=0)),
                ('reward_coins', models.PositiveSmallIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='content.level')),
            ],
            options={
                'ordering': ['level__order', 'order'],
                'constraints': [models.UniqueConstraint(fields=('level', 'order'), name='uniq_milestone_order')],
            },
        ),
    ]
