# Generated by Django 5.1.15 on 2026-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_unit_subtitle_levelmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='tier_label',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
