# Generated by Django 5.1.15 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_level_tier_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="path_subtitle_vi",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Dòng mô tả ngắn hiển thị trong Unit sheet của lộ trình.",
                max_length=160,
            ),
        ),
    ]
