# Generated by Django 5.1.15 on 2026-09-05

from django.db import migrations


def backfill_path_subtitles(apps, schema_editor):
    del schema_editor
    Lesson = apps.get_model("content", "Lesson")
    for lesson in Lesson.objects.filter(path_subtitle_vi="").exclude(description_vi="").iterator():
        lesson.path_subtitle_vi = lesson.description_vi.strip()[:160]
        lesson.save(update_fields=["path_subtitle_vi"])


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_lesson_path_subtitle_vi"),
    ]

    operations = [
        migrations.RunPython(backfill_path_subtitles, migrations.RunPython.noop),
    ]
