# Generated by Django 5.1.15 on 2026-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_backfill_lesson_path_subtitle_vi'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarpoint',
            name='note_vi',
            field=models.TextField(blank=True),
        ),
    ]
