# Generated by Django 5.1.15 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_grammarpoint_note_vi"),
    ]

    operations = [
        migrations.AddField(
            model_name="shadowingdeck",
            name="icon",
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
