# Generated by Django 5.1.15 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_shadowingdeck_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="shadowingsentence",
            name="highlights",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="shadowingsentence",
            name="speaking_goal_vi",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
