# Generated by Django 5.1.15 on 2026-09-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_shadowingsentence_speaking_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title_vi', models.CharField(max_length=128)),
                ('icon', models.CharField(blank=True, max_length=48)),
                ('est_seconds', models.PositiveIntegerField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listening_topics', to='content.level')),
            ],
            options={
                'ordering': ['level__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ListeningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text_en', models.CharField(max_length=512)),
                ('text_vi', models.CharField(blank=True, max_length=512)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('blank_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.listeningtopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='listeningtopic',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='uniq_listening_topic_order'),
        ),
    ]
