# Generated by Django 5.1.15 on 2026-09-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_listeningtopic_listeningitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadowingdeck',
            name='color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='shadowingdeck',
            name='icon_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
