# Generated by Django 5.1.15 on 2026-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_shadowingdeck_color_shadowingdeck_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtopic',
            name='color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='listeningtopic',
            name='icon_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
