# Generated by Django 5.1.15 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_listeningtopic_color_listeningtopic_icon_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabulary",
            name="definition_vi",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="antonyms",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
