# Generated by Django 5.1.15 on 2026-09-09 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_vocabulary_definition_vi_vocabulary_antonyms'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyDeckCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('title_vi', models.CharField(max_length=128)),
                ('chip_label_vi', models.CharField(blank=True, max_length=32)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title_vi', models.CharField(max_length=128)),
                ('cover_title', models.CharField(blank=True, max_length=64)),
                ('badge_vi', models.CharField(blank=True, max_length=32)),
                ('background_url', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('learner_base', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary_decks', to='content.level')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decks', to='content.vocabularydeckcollection')),
            ],
            options={
                'ordering': ['collection__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyDeckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.vocabularydeck')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_items', to='content.vocabulary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='vocabularydeck',
            name='vocabulary',
            field=models.ManyToManyField(related_name='decks', through='content.VocabularyDeckItem', to='content.vocabulary'),
        ),
        migrations.AddConstraint(
            model_name='vocabularydeckitem',
            constraint=models.UniqueConstraint(fields=('deck', 'vocabulary'), name='uniq_deck_vocab'),
        ),
    ]
