# Generated by Django 5.1.15 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_vocabularydeckcollection_vocabularydeck_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shadowingdeck",
            name="background_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
