# Generated by Django 5.1.15 on 2026-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_shadowingdeck_background_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularydeck',
            name='accent_color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='vocabularydeck',
            name='icon',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
