# Generated by Django 5.1.15 on 2026-09-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_vocabularydeck_accent_color_vocabularydeck_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipasound',
            name='category_en',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='category_vi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='examples',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='group',
            field=models.CharField(choices=[('monophthong', 'Nguyên âm đơn'), ('diphthong', 'Nguyên âm đôi'), ('voiceless', 'Phụ âm vô thanh'), ('voiced', 'Phụ âm hữu thanh'), ('nasal_approx', 'Âm mũi & bán nguyên âm')], default='monophthong', max_length=16),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='lips_vi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='tip_vi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='tongue_vi',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
