# Generated by Django 5.1.15 on 2026-09-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_ipa_sound_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordroot',
            name='effect_vi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='wordroot',
            name='group_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordroot',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordroot',
            name='samples',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
