# Generated by Django 5.1.15 on 2026-09-15 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_word_root_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarpoint',
            name='form_vi',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='formula_parts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='mistake_right',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='mistake_wrong',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='subtitle_vi',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='GrammarExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('prompt_en', models.CharField(max_length=255)),
                ('prompt_vi', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(default=list)),
                ('answer_index', models.PositiveSmallIntegerField(default=0)),
                ('explanation_vi', models.CharField(blank=True, max_length=255)),
                ('grammar_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='content.grammarpoint')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
