# Generated by Django 5.1.15 on 2026-09-16 03:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_grammar_exercises_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='video',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='error_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(choices=[('curated', 'Sayfully tuyển chọn'), ('user', 'Người dùng thêm')], default='curated', max_length=8),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('ready', 'Sẵn sàng'), ('failed', 'Lỗi')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='content.level'),
        ),
        migrations.CreateModel(
            name='UserVideoLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_library', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='content.video')),
            ],
            options={
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'video'), name='uniq_user_video')],
            },
        ),
    ]
