# Generated by Django 5.1.15 on 2026-09-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_video_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
