# Generated by Django 5.1.15 on 2026-09-18 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_accent_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('code', models.CharField(max_length=6, unique=True)),
                ('cefr_label', models.CharField(max_length=4)),
                ('gse_min', models.PositiveSmallIntegerField()),
                ('gse_max', models.PositiveSmallIntegerField()),
                ('title_vi', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['level__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BandGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CanDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('source', models.CharField(choices=[('cefr', 'CEFR Companion Volume'), ('gse_lo', 'GSE Learning Objective'), ('gse_gr', 'GSE Grammar Objective')], max_length=8)),
                ('cefr_label', models.CharField(max_length=6)),
                ('gse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skill', models.CharField(blank=True, max_length=128)),
                ('scale', models.CharField(blank=True, max_length=255)),
                ('can_do_vi', models.CharField(max_length=512)),
                ('can_do_en', models.CharField(max_length=512)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('is_speaking_core', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('code', models.SlugField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('license', models.CharField(blank=True, max_length=8)),
                ('usage', models.CharField(blank=True, max_length=12)),
                ('attribution', models.CharField(blank=True, max_length=512)),
                ('tos_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionExponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('examples', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title_en', models.CharField(max_length=160)),
                ('title_vi', models.CharField(blank=True, max_length=160)),
                ('section', models.CharField(blank=True, max_length=32)),
                ('levels', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LessonObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PronunciationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('category_en', models.CharField(blank=True, max_length=64)),
                ('category_vi', models.CharField(max_length=64)),
                ('feature_en', models.CharField(max_length=160)),
                ('status', models.CharField(max_length=10)),
                ('ipa', models.CharField(blank=True, max_length=96)),
                ('rule_en', models.TextField(blank=True)),
                ('rule_vi', models.TextField()),
                ('focus_en', models.TextField(blank=True)),
                ('focus_vi', models.TextField(blank=True)),
                ('examples_en', models.TextField(blank=True)),
                ('examples_vi', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('listening', 'Nghe'), ('reading', 'Đọc'), ('vocab', 'Từ vựng'), ('grammar', 'Ngữ pháp')], default='listening', max_length=10)),
                ('question_en', models.CharField(max_length=512)),
                ('question_vi', models.CharField(blank=True, max_length=512)),
                ('options', models.JSONField()),
                ('answer_index', models.PositiveSmallIntegerField()),
                ('explanation_vi', models.CharField(blank=True, max_length=512)),
                ('source_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('audio_us_path', models.CharField(blank=True, max_length=255)),
                ('audio_uk_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='vocabulary',
            name='uniq_headword_pos',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='context_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='guideword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='guideword_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='is_path_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='lexical_range',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='sub_category',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='super_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grammar_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_lessons', to='content.grammarpoint'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='gse',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source_ref',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='unit',
            name='gse_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='gse_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic'),
        ),
        migrations.AddField(
            model_name='unit',
            name='topic_en',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='unit',
            name='topic_vi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='category',
            field=models.CharField(default='word', max_length=16),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='gse',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='headword_us',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='is_path_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='sense',
            field=models.SlugField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='sense_label_en',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='usage_label',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='dialogueline',
            name='ipa',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='dialogueline',
            name='text_en',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='dialogueline',
            name='text_vi',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='lessonstep',
            name='kind',
            field=models.CharField(choices=[('intro', 'Giới thiệu'), ('vocab', 'Từ vựng'), ('grammar', 'Ngữ pháp'), ('dialogue', 'Hội thoại'), ('spelling', 'Luyện viết'), ('quiz', 'Luyện tập'), ('writing', 'Viết câu (AI)'), ('speak', 'Nói theo chức năng'), ('pron', 'Luyện phát âm'), ('listen', 'Nghe & nhại')], max_length=12),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='pos',
            field=models.CharField(choices=[('n', 'Danh từ'), ('v', 'Động từ'), ('adj', 'Tính từ'), ('adv', 'Trạng từ'), ('prep', 'Giới từ'), ('pron', 'Đại từ'), ('conj', 'Liên từ'), ('det', 'Từ hạn định'), ('excl', 'Thán từ'), ('num', 'Số từ'), ('phr', 'Cụm từ'), ('modal', 'Động từ khuyết thiếu'), ('aux', 'Trợ động từ')], max_length=6),
        ),
        migrations.AddField(
            model_name='band',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='content.level'),
        ),
        migrations.AddField(
            model_name='band',
            name='milestone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band', to='content.levelmilestone'),
        ),
        migrations.AddField(
            model_name='unit',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='content.band'),
        ),
        migrations.AddField(
            model_name='bandgoal',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='content.band'),
        ),
        migrations.AddField(
            model_name='cando',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='can_dos', to='content.level'),
        ),
        migrations.AddField(
            model_name='bandgoal',
            name='can_do',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.cando'),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='grammar_points', to='content.cando'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contentsource'),
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(fields=('headword', 'pos', 'sense'), name='uniq_headword_pos_sense'),
        ),
        migrations.AddField(
            model_name='functionexponent',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.level'),
        ),
        migrations.AddField(
            model_name='functionexponent',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exponents', to='content.languagefunction'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='speaking_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='content.languagefunction'),
        ),
        migrations.AddField(
            model_name='unit',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='content.languagefunction'),
        ),
        migrations.AddField(
            model_name='lessonobjective',
            name='can_do',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='content.cando'),
        ),
        migrations.AddField(
            model_name='lessonobjective',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='pronunciationfeature',
            name='sounds',
            field=models.ManyToManyField(blank=True, related_name='features', to='content.ipasound'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pronunciation_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='content.pronunciationfeature'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='content.lesson'),
        ),
        migrations.AddConstraint(
            model_name='band',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='uniq_band_order'),
        ),
        migrations.AddIndex(
            model_name='cando',
            index=models.Index(fields=['level', 'skill', 'gse'], name='cando_level_skill_gse_idx'),
        ),
        migrations.AddConstraint(
            model_name='bandgoal',
            constraint=models.UniqueConstraint(fields=('band', 'can_do'), name='uniq_band_cando'),
        ),
        migrations.AddConstraint(
            model_name='functionexponent',
            constraint=models.UniqueConstraint(fields=('function', 'level'), name='uniq_exponent_level'),
        ),
        migrations.AddConstraint(
            model_name='lessonobjective',
            constraint=models.UniqueConstraint(fields=('lesson', 'can_do'), name='uniq_lesson_cando'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='uniq_quiz_order'),
        ),
    ]
