# Generated by Django 5.1.15 on 2026-09-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0025_path_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="formula",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="hint_vi",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="sentence_en",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="sentence_vi",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="speaker",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="kind",
            field=models.CharField(
                choices=[
                    ("listening", "Nghe rồi chọn"),
                    ("reading", "Đọc"),
                    ("vocab", "Nghĩa của từ"),
                    ("cloze", "Điền từ theo audio"),
                    ("grammar", "Chọn câu đúng ngữ pháp"),
                    ("reorder", "Sắp xếp từ"),
                ],
                default="listening",
                max_length=10,
            ),
        ),
    ]
