# Generated by Django 5.1.15 on 2026-09-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0026_quiz_kinds"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogue",
            name="excerpt_end",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dialogue",
            name="excerpt_start",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
