# Generated by Django 5.1.15 on 2026-09-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_dialogue_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='kind',
            field=models.CharField(choices=[('lesson', 'Bài học'), ('checkpoint', 'Kiểm tra unit')], default='lesson', max_length=12),
        ),
    ]
