# Generated by Django 5.1.15 on 2026-09-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0028_lesson_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="pronunciationfeature",
            name="title_vi",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
