# Generated by Django 5.1.15 on 2026-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_pron_title_vi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cando',
            name='source',
            field=models.CharField(choices=[('cefr', 'CEFR Companion Volume'), ('gse_lo', 'GSE Learning Objective'), ('gse_gr', 'GSE Grammar Objective'), ('sayfully', 'Mục tiêu bài học Sayfully')], max_length=8),
        ),
    ]
