# Generated by Django 5.1.15 on 2026-09-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_cando_source_sayfully'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
