# Generated by Django 5.1.15 on 2026-09-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarexercise',
            name='answer_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='grammarexercise',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grammarexercise',
            name='kind',
            field=models.CharField(choices=[('choice', 'Trắc nghiệm dạng đúng'), ('order', 'Sắp xếp trật tự từ'), ('blank', 'Điền từ vào chỗ trống'), ('fix', 'Sửa lỗi người Việt')], default='choice', max_length=8),
        ),
        migrations.AddField(
            model_name='grammarpoint',
            name='lesson_code',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='acoustic_vi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='drill_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='drill_vi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ipasound',
            name='practice_words',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='listeningitem',
            name='phase',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listeningitem',
            name='skill_vi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='listeningitem',
            name='tip_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listeningitem',
            name='trap_vi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='listeningitem',
            name='word_class_vi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reading',
            name='code',
            field=models.SlugField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='reading',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shadowingsentence',
            name='context_vi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shadowingsentence',
            name='phase',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shadowingsentence',
            name='phonetic_note_vi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shadowingsentence',
            name='speech_act_vi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vocabularydeck',
            name='description_vi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vocabularydeckitem',
            name='group_vi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='wordroot',
            name='family',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='wordroot',
            name='practice',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='wordroot',
            name='practice_is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grammarexercise',
            name='explanation_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grammarexercise',
            name='prompt_en',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='grammarexercise',
            name='prompt_vi',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
