# Generated by Django 5.1.15 on 2026-09-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0033_review_skills_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="listeningtopic",
            name="background_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="listeningtopic",
            name="focus_vi",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
