# Generated by Django 5.1.15 on 2026-09-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_listeningtopic_card_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary', to='content.level'),
        ),
    ]
