# Generated by Django 5.1.15 on 2026-09-25 10:57

from django.db import migrations, models

from apps.common.learning_goals import deck_goals, video_category_goals


def backfill(apps, schema_editor):
    """Điền mục tiêu cho bộ thẻ, chủ đề video đã có bằng quy tắc mặc định; lần nạp sheet sau ghi đè."""
    for deck in apps.get_model("content", "VocabularyDeck").objects.all():
        deck.learning_goals = deck_goals(deck.code)
        deck.save(update_fields=["learning_goals"])
    for cat in apps.get_model("content", "VideoCategory").objects.all():
        cat.learning_goals = video_category_goals(cat.slug, cat.name)
        cat.save(update_fields=["learning_goals"])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_vocabulary_level_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='learning_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='vocabularydeck',
            name='learning_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
