"""
DEV ONLY — nạp từ vựng mẫu cho 6 cấp CEFR để test path map của mini-game.

Idempotent: upsert theo ``(headword, pos)`` giống ``import_vocab``. Chỉ ghi các
trường tối thiểu mà game cần (``headword``, ``pos``, ``level``, ``meaning_vi``,
``frequency_rank``) — không đụng IPA/audio/ví dụ, nên chạy lại sau khi đã có dữ
liệu thật cũng không xoá mất gì.

    python manage.py seed_wordrain_vocab            # nạp / cập nhật
    python manage.py seed_wordrain_vocab --stats    # chỉ đếm, không ghi
    python manage.py seed_wordrain_vocab --clear    # xoá đúng các từ do lệnh này tạo
"""

from django.core.management.base import BaseCommand
from django.db import transaction

from apps.content.models import Level, Vocabulary

# Mỗi dòng: "headword|pos|nghĩa tiếng Việt"
WORDS: dict[str, list[str]] = {
    "A1": [
        "apple|n|quả táo", "book|n|quyển sách",
        "water|n|nước", "sun|n|mặt trời",
        "cat|n|con mèo", "house|n|ngôi nhà",
        "school|n|trường học", "friend|n|người bạn",
        "flower|n|bông hoa", "bread|n|bánh mì",
        "bird|n|con chim", "tree|n|cái cây",
        "milk|n|sữa", "chair|n|cái ghế",
        "dog|n|con chó", "fish|n|con cá",
        "table|n|cái bàn", "door|n|cửa ra vào",
        "window|n|cửa sổ", "car|n|xe hơi",
        "bus|n|xe buýt", "city|n|thành phố",
        "room|n|căn phòng", "family|n|gia đình",
        "mother|n|mẹ", "father|n|bố",
        "sister|n|chị em gái", "brother|n|anh em trai",
        "baby|n|em bé", "boy|n|cậu bé",
        "girl|n|cô bé", "man|n|người đàn ông",
        "woman|n|người phụ nữ", "name|n|tên",
        "day|n|ngày", "night|n|ban đêm",
        "week|n|tuần", "month|n|tháng",
        "year|n|năm", "time|n|thời gian",
        "morning|n|buổi sáng", "evening|n|buổi tối",
        "food|n|thức ăn", "rice|n|cơm, gạo",
        "egg|n|quả trứng", "meat|n|thịt",
        "fruit|n|trái cây", "tea|n|trà",
        "coffee|n|cà phê", "juice|n|nước ép",
        "sugar|n|đường", "salt|n|muối",
        "plate|n|cái đĩa", "cup|n|cái cốc",
        "spoon|n|cái thìa", "knife|n|con dao",
        "bed|n|cái giường", "floor|n|sàn nhà",
        "wall|n|bức tường", "garden|n|khu vườn",
        "park|n|công viên", "street|n|đường phố",
        "shop|n|cửa hàng", "supermarket|n|siêu thị",
        "money|n|tiền", "price|n|giá",
        "bag|n|cái túi", "box|n|cái hộp",
        "key|n|chìa khoá", "phone|n|điện thoại",
        "computer|n|máy tính", "pen|n|cây bút",
        "pencil|n|bút chì", "paper|n|giấy",
        "picture|n|bức tranh", "music|n|âm nhạc",
        "film|n|bộ phim", "game|n|trò chơi",
        "ball|n|quả bóng", "shoe|n|chiếc giày",
        "shirt|n|cái áo sơ mi", "hat|n|cái mũ",
        "coat|n|áo khoác", "dress|n|váy",
        "hand|n|bàn tay", "head|n|cái đầu",
        "eye|n|con mắt", "ear|n|cái tai",
        "mouth|n|cái miệng", "nose|n|cái mũi",
        "foot|n|bàn chân", "hair|n|tóc",
        "face|n|khuôn mặt", "arm|n|cánh tay",
        "leg|n|cái chân", "body|n|cơ thể",
        "doctor|n|bác sĩ", "teacher|n|giáo viên",
        "student|n|học sinh", "job|n|công việc",
        "class|n|lớp học", "lesson|n|bài học",
        "word|n|từ", "question|n|câu hỏi",
        "letter|n|lá thư", "number|n|con số",
        "colour|n|màu sắc", "weather|n|thời tiết",
        "rain|n|mưa", "snow|n|tuyết",
        "wind|n|gió", "cloud|n|đám mây",
        "sky|n|bầu trời", "sea|n|biển",
        "river|n|dòng sông", "mountain|n|ngọn núi",
        "beach|n|bãi biển", "animal|n|động vật",
        "horse|n|con ngựa", "cow|n|con bò",
        "chicken|n|con gà", "country|n|đất nước",
        "language|n|ngôn ngữ", "holiday|n|kỳ nghỉ",
        "weekend|n|cuối tuần", "party|n|bữa tiệc",
        "birthday|n|sinh nhật", "gift|n|món quà",
        "eat|v|ăn", "drink|v|uống",
        "sleep|v|ngủ", "run|v|chạy",
        "walk|v|đi bộ", "come|v|đến",
        "see|v|nhìn thấy", "hear|v|nghe thấy",
        "speak|v|nói", "read|v|đọc",
        "write|v|viết", "play|v|chơi",
        "work|v|làm việc", "live|v|sống",
        "love|v|yêu", "like|v|thích",
        "want|v|muốn", "need|v|cần",
        "make|v|làm ra", "take|v|lấy",
        "give|v|cho", "buy|v|mua",
        "sell|v|bán", "open|v|mở",
        "close|v|đóng", "start|v|bắt đầu",
        "stop|v|dừng lại", "help|v|giúp đỡ",
        "learn|v|học", "teach|v|dạy",
        "know|v|biết", "think|v|nghĩ",
        "ask|v|hỏi", "answer|v|trả lời",
        "call|v|gọi", "wait|v|chờ",
        "find|v|tìm thấy", "sit|v|ngồi",
        "stand|v|đứng", "wash|v|rửa",
        "cook|v|nấu ăn", "clean|v|lau dọn",
        "drive|v|lái xe", "swim|v|bơi",
        "sing|v|hát", "dance|v|nhảy múa",
        "watch|v|xem", "listen|v|lắng nghe",
        "study|v|học tập", "travel|v|đi du lịch",
        "big|adj|to lớn", "small|adj|nhỏ",
        "good|adj|tốt", "bad|adj|tệ",
        "new|adj|mới", "old|adj|cũ, già",
        "hot|adj|nóng", "cold|adj|lạnh",
        "happy|adj|vui vẻ", "sad|adj|buồn",
        "fast|adj|nhanh", "slow|adj|chậm",
        "long|adj|dài", "short|adj|ngắn",
        "tall|adj|cao", "easy|adj|dễ",
        "difficult|adj|khó", "beautiful|adj|đẹp",
        "clean|adj|sạch sẽ", "dirty|adj|bẩn",
        "young|adj|trẻ", "rich|adj|giàu",
        "poor|adj|nghèo", "hungry|adj|đói",
        "thirsty|adj|khát", "tired|adj|mệt",
        "busy|adj|bận rộn", "free|adj|rảnh, miễn phí",
        "same|adj|giống nhau", "different|adj|khác nhau",
        "green|adj|màu xanh lá", "red|adj|màu đỏ",
        "blue|adj|màu xanh dương", "black|adj|màu đen",
        "white|adj|màu trắng", "yellow|adj|màu vàng",
        "now|adv|bây giờ", "today|adv|hôm nay",
        "tomorrow|adv|ngày mai", "yesterday|adv|hôm qua",
        "always|adv|luôn luôn", "never|adv|không bao giờ",
        "often|adv|thường xuyên", "sometimes|adv|thỉnh thoảng",
        "very|adv|rất",
    ],
    "A2": [
        "luggage|n|hành lý", "journey|n|chuyến đi",
        "reservation|n|việc đặt chỗ", "receipt|n|hoá đơn",
        "direction|n|phương hướng", "menu|n|thực đơn",
        "ticket|n|vé", "station|n|nhà ga",
        "waiter|n|bồi bàn", "passport|n|hộ chiếu",
        "airport|n|sân bay", "flight|n|chuyến bay",
        "hotel|n|khách sạn", "address|n|địa chỉ",
        "neighbour|n|hàng xóm", "customer|n|khách hàng",
        "manager|n|quản lý", "office|n|văn phòng",
        "meeting|n|cuộc họp", "message|n|tin nhắn",
        "email|n|thư điện tử", "website|n|trang web",
        "problem|n|vấn đề", "reason|n|lý do",
        "idea|n|ý tưởng", "plan|n|kế hoạch",
        "advice|n|lời khuyên", "example|n|ví dụ",
        "mistake|n|lỗi sai", "accident|n|tai nạn",
        "health|n|sức khoẻ", "medicine|n|thuốc",
        "hospital|n|bệnh viện", "exercise|n|bài tập, việc tập luyện",
        "sport|n|thể thao", "team|n|đội",
        "match|n|trận đấu", "player|n|cầu thủ",
        "prize|n|giải thưởng", "hobby|n|sở thích",
        "camera|n|máy ảnh", "magazine|n|tạp chí",
        "newspaper|n|tờ báo", "story|n|câu chuyện",
        "history|n|lịch sử", "science|n|khoa học",
        "subject|n|môn học", "exam|n|kỳ thi",
        "result|n|kết quả", "degree|n|bằng cấp",
        "university|n|trường đại học", "library|n|thư viện",
        "museum|n|bảo tàng", "theatre|n|nhà hát",
        "restaurant|n|nhà hàng", "kitchen|n|nhà bếp",
        "bathroom|n|phòng tắm", "furniture|n|đồ nội thất",
        "building|n|toà nhà", "village|n|ngôi làng",
        "island|n|hòn đảo", "forest|n|khu rừng",
        "field|n|cánh đồng", "farm|n|nông trại",
        "traffic|n|giao thông", "bridge|n|cây cầu",
        "corner|n|góc", "middle|n|ở giữa",
        "future|n|tương lai", "past|n|quá khứ",
        "moment|n|khoảnh khắc", "season|n|mùa",
        "temperature|n|nhiệt độ", "storm|n|cơn bão",
        "sound|n|âm thanh", "smell|n|mùi",
        "taste|n|vị", "size|n|kích cỡ",
        "weight|n|cân nặng", "shape|n|hình dạng",
        "borrow|v|mượn", "arrive|v|đến nơi",
        "choose|v|lựa chọn", "book|v|đặt chỗ",
        "pay|v|trả tiền", "cost|v|có giá",
        "spend|v|tiêu, dành ra", "save|v|tiết kiệm",
        "lend|v|cho mượn", "return|v|trả lại",
        "carry|v|mang, vác", "bring|v|mang đến",
        "send|v|gửi", "receive|v|nhận",
        "invite|v|mời", "visit|v|thăm",
        "meet|v|gặp gỡ", "join|v|tham gia",
        "leave|v|rời đi", "arrange|v|sắp xếp",
        "prepare|v|chuẩn bị", "practise|v|luyện tập",
        "improve|v|cải thiện", "explain|v|giải thích",
        "describe|v|mô tả", "compare|v|so sánh",
        "decide|v|quyết định", "agree|v|đồng ý",
        "refuse|v|từ chối", "promise|v|hứa",
        "remember|v|nhớ", "forget|v|quên",
        "believe|v|tin", "hope|v|hy vọng",
        "worry|v|lo lắng", "enjoy|v|tận hưởng",
        "prefer|v|thích hơn", "hate|v|ghét",
        "miss|v|nhớ, bỏ lỡ", "change|v|thay đổi",
        "repair|v|sửa chữa", "build|v|xây dựng",
        "grow|v|trồng, lớn lên", "happen|v|xảy ra",
        "follow|v|đi theo", "climb|v|leo trèo",
        "jump|v|nhảy", "fall|v|ngã, rơi",
        "throw|v|ném", "catch|v|bắt",
        "push|v|đẩy", "pull|v|kéo",
        "crowded|adj|đông đúc", "healthy|adj|lành mạnh",
        "quiet|adj|yên tĩnh", "noisy|adj|ồn ào",
        "safe|adj|an toàn", "dangerous|adj|nguy hiểm",
        "famous|adj|nổi tiếng", "popular|adj|được ưa chuộng",
        "modern|adj|hiện đại", "traditional|adj|truyền thống",
        "cheap|adj|rẻ", "expensive|adj|đắt",
        "comfortable|adj|thoải mái", "boring|adj|nhàm chán",
        "interesting|adj|thú vị", "exciting|adj|hào hứng",
        "friendly|adj|thân thiện", "polite|adj|lịch sự",
        "rude|adj|thô lỗ", "honest|adj|trung thực",
        "careful|adj|cẩn thận", "lazy|adj|lười biếng",
        "clever|adj|thông minh", "strange|adj|kỳ lạ",
        "empty|adj|trống rỗng", "full|adj|đầy",
        "heavy|adj|nặng", "light|adj|nhẹ",
        "wide|adj|rộng", "narrow|adj|hẹp",
        "deep|adj|sâu", "strong|adj|mạnh",
        "weak|adj|yếu", "possible|adj|có thể",
        "ready|adj|sẵn sàng", "similar|adj|tương tự",
        "useful|adj|hữu ích", "usually|adv|thường thì",
        "already|adv|đã rồi", "still|adv|vẫn còn",
        "almost|adv|gần như", "together|adv|cùng nhau",
        "abroad|adv|ở nước ngoài", "quickly|adv|một cách nhanh chóng",
        "slowly|adv|một cách chậm rãi", "carefully|adv|một cách cẩn thận",
        "suddenly|adv|đột nhiên",
    ],
    "B1": [
        "deadline|n|hạn chót", "opportunity|n|cơ hội",
        "environment|n|môi trường", "benefit|n|lợi ích",
        "solution|n|giải pháp", "responsibility|n|trách nhiệm",
        "challenge|n|thử thách", "colleague|n|đồng nghiệp",
        "career|n|sự nghiệp", "salary|n|tiền lương",
        "contract|n|hợp đồng", "interview|n|cuộc phỏng vấn",
        "experience|n|kinh nghiệm", "skill|n|kỹ năng",
        "knowledge|n|kiến thức", "progress|n|tiến bộ",
        "success|n|thành công", "failure|n|thất bại",
        "effort|n|nỗ lực", "purpose|n|mục đích",
        "method|n|phương pháp", "process|n|quá trình",
        "system|n|hệ thống", "structure|n|cấu trúc",
        "quality|n|chất lượng", "quantity|n|số lượng",
        "amount|n|lượng", "average|n|mức trung bình",
        "percentage|n|tỷ lệ phần trăm", "research|n|nghiên cứu",
        "evidence|n|bằng chứng", "argument|n|lập luận",
        "opinion|n|ý kiến", "attitude|n|thái độ",
        "behaviour|n|hành vi", "relationship|n|mối quan hệ",
        "community|n|cộng đồng", "society|n|xã hội",
        "government|n|chính phủ", "policy|n|chính sách",
        "law|n|luật pháp", "right|n|quyền lợi",
        "duty|n|nghĩa vụ", "citizen|n|công dân",
        "population|n|dân số", "economy|n|nền kinh tế",
        "industry|n|ngành công nghiệp", "product|n|sản phẩm",
        "service|n|dịch vụ", "market|n|thị trường",
        "profit|n|lợi nhuận", "budget|n|ngân sách",
        "investment|n|khoản đầu tư", "technology|n|công nghệ",
        "device|n|thiết bị", "software|n|phần mềm",
        "network|n|mạng lưới", "data|n|dữ liệu",
        "source|n|nguồn", "culture|n|văn hoá",
        "tradition|n|truyền thống", "religion|n|tôn giáo",
        "generation|n|thế hệ", "childhood|n|tuổi thơ",
        "memory|n|ký ức", "emotion|n|cảm xúc",
        "stress|n|căng thẳng", "pressure|n|áp lực",
        "confidence|n|sự tự tin", "patience|n|sự kiên nhẫn",
        "courage|n|lòng dũng cảm", "achieve|v|đạt được",
        "persuade|v|thuyết phục", "negotiate|v|đàm phán",
        "manage|v|quản lý", "organise|v|tổ chức",
        "develop|v|phát triển", "produce|v|sản xuất",
        "provide|v|cung cấp", "supply|v|cung ứng",
        "reduce|v|giảm bớt", "increase|v|tăng lên",
        "affect|v|ảnh hưởng", "cause|v|gây ra",
        "prevent|v|ngăn chặn", "avoid|v|tránh",
        "protect|v|bảo vệ", "support|v|ủng hộ",
        "encourage|v|khuyến khích", "suggest|v|đề xuất",
        "recommend|v|khuyên dùng", "consider|v|cân nhắc",
        "realise|v|nhận ra", "recognise|v|nhận biết",
        "discover|v|khám phá", "examine|v|kiểm tra",
        "measure|v|đo lường", "estimate|v|ước tính",
        "predict|v|dự đoán", "assume|v|cho rằng",
        "conclude|v|kết luận", "prove|v|chứng minh",
        "admit|v|thừa nhận", "deny|v|phủ nhận",
        "complain|v|phàn nàn", "apologise|v|xin lỗi",
        "warn|v|cảnh báo", "announce|v|thông báo",
        "publish|v|xuất bản", "translate|v|dịch",
        "replace|v|thay thế", "repeat|v|lặp lại",
        "continue|v|tiếp tục", "survive|v|sống sót",
        "succeed|v|thành công", "reliable|adj|đáng tin cậy",
        "confident|adj|tự tin", "efficient|adj|hiệu quả",
        "creative|adj|sáng tạo", "flexible|adj|linh hoạt",
        "patient|adj|kiên nhẫn", "ambitious|adj|tham vọng",
        "generous|adj|hào phóng", "selfish|adj|ích kỷ",
        "serious|adj|nghiêm túc", "curious|adj|tò mò",
        "anxious|adj|lo âu", "aware|adj|nhận thức được",
        "responsible|adj|có trách nhiệm", "independent|adj|độc lập",
        "essential|adj|thiết yếu", "obvious|adj|hiển nhiên",
        "typical|adj|điển hình", "specific|adj|cụ thể",
        "general|adj|chung", "particular|adj|riêng biệt",
        "various|adj|đa dạng", "common|adj|phổ biến",
        "rare|adj|hiếm", "accurate|adj|chính xác",
        "complex|adj|phức tạp", "significant|adj|đáng kể",
        "valuable|adj|có giá trị", "effective|adj|hiệu lực",
        "practical|adj|thực tiễn", "reasonable|adj|hợp lý",
        "fair|adj|công bằng", "guilty|adj|có tội",
        "willing|adj|sẵn lòng", "capable|adj|có khả năng",
        "however|adv|tuy nhiên", "therefore|adv|do đó",
        "instead|adv|thay vào đó", "eventually|adv|cuối cùng thì",
        "recently|adv|gần đây", "probably|adv|có lẽ",
        "certainly|adv|chắc chắn", "especially|adv|đặc biệt là",
        "rarely|adv|hiếm khi", "hardly|adv|hầu như không",
    ],
    "B2": [
        "consequence|n|hậu quả", "circumstance|n|hoàn cảnh",
        "assumption|n|giả định", "perspective|n|góc nhìn",
        "priority|n|ưu tiên", "criterion|n|tiêu chí",
        "framework|n|khung sườn", "strategy|n|chiến lược",
        "initiative|n|sáng kiến", "objective|n|mục tiêu",
        "outcome|n|kết quả đầu ra", "impact|n|tác động",
        "trend|n|xu hướng", "shift|n|sự chuyển dịch",
        "decline|n|sự sụt giảm", "growth|n|sự tăng trưởng",
        "expansion|n|sự mở rộng", "shortage|n|sự thiếu hụt",
        "surplus|n|phần dư thừa", "resource|n|nguồn lực",
        "asset|n|tài sản", "liability|n|khoản nợ, trách nhiệm pháp lý",
        "stakeholder|n|bên liên quan", "competitor|n|đối thủ cạnh tranh",
        "negotiation|n|cuộc đàm phán", "compromise|n|sự thoả hiệp",
        "conflict|n|xung đột", "dispute|n|tranh chấp",
        "agreement|n|thoả thuận", "regulation|n|quy định",
        "requirement|n|yêu cầu", "restriction|n|hạn chế",
        "obligation|n|nghĩa vụ", "privilege|n|đặc quyền",
        "incentive|n|động lực khuyến khích", "reward|n|phần thưởng",
        "penalty|n|hình phạt", "welfare|n|phúc lợi",
        "poverty|n|nghèo đói", "inequality|n|bất bình đẳng",
        "discrimination|n|sự phân biệt đối xử", "diversity|n|sự đa dạng",
        "identity|n|bản sắc", "reputation|n|danh tiếng",
        "influence|n|ảnh hưởng", "authority|n|thẩm quyền",
        "hierarchy|n|hệ thống thứ bậc", "bureaucracy|n|bộ máy quan liêu",
        "infrastructure|n|cơ sở hạ tầng", "sustainability|n|tính bền vững",
        "emission|n|khí thải", "pollution|n|ô nhiễm",
        "conservation|n|sự bảo tồn", "habitat|n|môi trường sống",
        "species|n|loài", "climate|n|khí hậu",
        "drought|n|hạn hán", "epidemic|n|dịch bệnh",
        "diagnosis|n|chẩn đoán", "treatment|n|liệu trình",
        "symptom|n|triệu chứng", "hypothesis|n|giả thuyết",
        "analysis|n|sự phân tích", "statistics|n|số liệu thống kê",
        "variable|n|biến số", "correlation|n|mối tương quan",
        "bias|n|thiên kiến", "controversy|n|tranh cãi",
        "phenomenon|n|hiện tượng", "insight|n|sự thấu hiểu",
        "acknowledge|v|thừa nhận", "emphasise|v|nhấn mạnh",
        "highlight|v|làm nổi bật", "illustrate|v|minh hoạ",
        "demonstrate|v|chứng tỏ", "indicate|v|chỉ ra",
        "imply|v|ngụ ý", "interpret|v|diễn giải",
        "clarify|v|làm rõ", "justify|v|biện minh",
        "evaluate|v|đánh giá", "assess|v|thẩm định",
        "monitor|v|giám sát", "implement|v|triển khai",
        "establish|v|thiết lập", "maintain|v|duy trì",
        "sustain|v|duy trì lâu dài", "enhance|v|nâng cao",
        "optimise|v|tối ưu hoá", "minimise|v|giảm thiểu",
        "eliminate|v|loại bỏ", "overcome|v|vượt qua",
        "tackle|v|xử lý", "address|v|giải quyết",
        "allocate|v|phân bổ", "distribute|v|phân phối",
        "generate|v|tạo ra", "accumulate|v|tích luỹ",
        "fluctuate|v|dao động", "deteriorate|v|xấu đi",
        "undermine|v|làm suy yếu", "exaggerate|v|phóng đại",
        "underestimate|v|đánh giá thấp", "anticipate|v|dự liệu",
        "postpone|v|hoãn lại", "abandon|v|từ bỏ",
        "pursue|v|theo đuổi", "adapt|v|thích nghi",
        "cope|v|đối phó", "contribute|v|đóng góp",
        "collaborate|v|hợp tác", "coordinate|v|điều phối",
        "delegate|v|uỷ quyền", "supervise|v|giám sát",
        "criticise|v|phê bình", "comprehensive|adj|toàn diện",
        "substantial|adj|đáng kể", "considerable|adj|khá lớn",
        "adequate|adj|đầy đủ", "sufficient|adj|đủ dùng",
        "inevitable|adj|không thể tránh khỏi", "crucial|adj|then chốt",
        "vital|adj|sống còn", "relevant|adj|liên quan",
        "consistent|adj|nhất quán", "coherent|adj|mạch lạc",
        "ambiguous|adj|mơ hồ", "controversial|adj|gây tranh cãi",
        "feasible|adj|khả thi", "viable|adj|có thể tồn tại",
        "beneficial|adj|có lợi", "detrimental|adj|có hại",
        "vulnerable|adj|dễ bị tổn thương", "resilient|adj|kiên cường",
        "prominent|adj|nổi bật", "subtle|adj|tinh tế",
        "profound|adj|sâu sắc", "genuine|adj|chân thật",
        "deliberate|adj|có chủ ý", "arbitrary|adj|tuỳ tiện",
        "rigid|adj|cứng nhắc", "diverse|adj|đa dạng",
        "widespread|adj|lan rộng", "abundant|adj|dồi dào",
        "scarce|adj|khan hiếm", "redundant|adj|dư thừa",
        "obsolete|adj|lỗi thời", "innovative|adj|đổi mới",
        "nevertheless|adv|tuy vậy", "furthermore|adv|hơn nữa",
        "consequently|adv|do đó", "moreover|adv|ngoài ra",
        "regardless|adv|bất kể", "arguably|adv|có thể lập luận rằng",
        "presumably|adv|có lẽ là", "notably|adv|đáng chú ý là",
        "primarily|adv|chủ yếu", "ultimately|adv|rốt cuộc",
    ],
    "C1": [
        "nuance|n|sắc thái tinh tế", "paradigm|n|hệ hình, khuôn mẫu",
        "premise|n|tiền đề", "rationale|n|cơ sở lý luận",
        "paradox|n|nghịch lý", "dilemma|n|tình thế tiến thoái lưỡng nan",
        "discrepancy|n|sự chênh lệch", "anomaly|n|điều bất thường",
        "constraint|n|ràng buộc", "trade-off|n|sự đánh đổi",
        "leverage|n|đòn bẩy", "momentum|n|đà",
        "threshold|n|ngưỡng", "spectrum|n|phổ, dải",
        "consensus|n|sự đồng thuận", "coalition|n|liên minh",
        "advocate|n|người vận động", "sceptic|n|người hoài nghi",
        "proponent|n|người ủng hộ", "critic|n|nhà phê bình",
        "scrutiny|n|sự soi xét kỹ", "accountability|n|trách nhiệm giải trình",
        "transparency|n|tính minh bạch", "integrity|n|sự chính trực",
        "credibility|n|độ tin cậy", "legitimacy|n|tính chính danh",
        "sovereignty|n|chủ quyền", "jurisdiction|n|quyền tài phán",
        "precedent|n|tiền lệ", "mandate|n|sự uỷ nhiệm",
        "sanction|n|lệnh trừng phạt", "backlash|n|phản ứng dữ dội",
        "turmoil|n|sự hỗn loạn", "recession|n|suy thoái kinh tế",
        "inflation|n|lạm phát", "volatility|n|sự biến động mạnh",
        "speculation|n|sự đầu cơ", "monopoly|n|độc quyền",
        "subsidy|n|khoản trợ cấp", "deficit|n|thâm hụt",
        "revenue|n|doanh thu", "overhead|n|chi phí vận hành",
        "aggregate|n|tổng gộp", "proxy|n|đại diện thay thế",
        "catalyst|n|chất xúc tác", "trajectory|n|quỹ đạo",
        "milestone|n|cột mốc", "bottleneck|n|nút thắt cổ chai",
        "redundancy|n|sự dư thừa", "contingency|n|phương án dự phòng",
        "prerequisite|n|điều kiện tiên quyết", "aftermath|n|hậu quả sau sự kiện",
        "legacy|n|di sản", "connotation|n|hàm ý",
        "rhetoric|n|thuật hùng biện", "narrative|n|lối tường thuật",
        "propaganda|n|tuyên truyền", "stereotype|n|định kiến rập khuôn",
        "empathy|n|sự đồng cảm", "resilience|n|sức bật",
        "complacency|n|sự tự mãn", "scepticism|n|thái độ hoài nghi",
        "prejudice|n|thành kiến", "compliance|n|sự tuân thủ",
        "deterrent|n|yếu tố răn đe", "incentivise|v|tạo động lực",
        "advocate|v|vận động ủng hộ", "attribute|v|quy cho",
        "correlate|v|tương quan", "extrapolate|v|ngoại suy",
        "substantiate|v|chứng thực", "refute|v|bác bỏ",
        "reconcile|v|dung hoà", "mitigate|v|giảm nhẹ",
        "exacerbate|v|làm trầm trọng thêm", "alleviate|v|xoa dịu",
        "consolidate|v|củng cố", "diversify|v|đa dạng hoá",
        "streamline|v|tinh gọn", "outsource|v|thuê ngoài",
        "scrutinise|v|soi xét kỹ", "circumvent|v|lách qua",
        "perpetuate|v|kéo dài mãi", "erode|v|bào mòn",
        "amplify|v|khuếch đại", "diminish|v|làm suy giảm",
        "curtail|v|cắt giảm", "impose|v|áp đặt",
        "enforce|v|thực thi", "waive|v|miễn trừ",
        "endorse|v|tán thành", "denounce|v|lên án",
        "condemn|v|kết án", "contemplate|v|ngẫm nghĩ",
        "speculate|v|suy đoán", "envisage|v|hình dung",
        "foster|v|nuôi dưỡng", "cultivate|v|vun đắp",
        "harness|v|khai thác", "deploy|v|triển khai",
        "compile|v|biên soạn", "synthesise|v|tổng hợp",
        "discern|v|phân biệt rõ", "meticulous|adj|tỉ mỉ",
        "rigorous|adj|nghiêm ngặt", "pragmatic|adj|thực dụng",
        "nuanced|adj|nhiều sắc thái", "compelling|adj|thuyết phục mạnh mẽ",
        "plausible|adj|nghe hợp lý", "tentative|adj|dè dặt, tạm thời",
        "provisional|adj|tạm thời", "intrinsic|adj|thuộc về bản chất",
        "inherent|adj|vốn có", "explicit|adj|rõ ràng, tường minh",
        "implicit|adj|ngầm hiểu", "unprecedented|adj|chưa từng có",
        "unequivocal|adj|dứt khoát", "indispensable|adj|không thể thiếu",
        "negligible|adj|không đáng kể", "marginal|adj|biên, không đáng kể",
        "disproportionate|adj|không tương xứng", "cumulative|adj|tích luỹ",
        "systematic|adj|có hệ thống", "empirical|adj|dựa trên thực nghiệm",
        "theoretical|adj|thuộc lý thuyết", "conceptual|adj|thuộc khái niệm",
        "hypothetical|adj|mang tính giả định", "contentious|adj|gây tranh cãi",
        "prevalent|adj|phổ biến rộng", "sporadic|adj|rải rác",
        "chronic|adj|kinh niên", "acute|adj|cấp tính, gay gắt",
        "lucrative|adj|sinh lời", "austere|adj|khắc khổ",
        "versatile|adj|đa năng", "articulate|adj|diễn đạt lưu loát",
        "eloquent|adj|hùng hồn", "conversely|adv|ngược lại",
        "accordingly|adv|theo đó", "invariably|adv|luôn luôn không đổi",
        "predominantly|adv|phần lớn", "inherently|adv|vốn dĩ",
        "explicitly|adv|một cách rõ ràng",
    ],
    "C2": [
        "epitome|n|hình mẫu điển hình", "quintessence|n|tinh tuý",
        "juxtaposition|n|sự đặt cạnh nhau tương phản", "dichotomy|n|sự phân đôi đối lập",
        "conundrum|n|câu hỏi hóc búa", "quandary|n|tình thế khó xử",
        "impasse|n|thế bế tắc", "watershed|n|bước ngoặt",
        "hallmark|n|dấu ấn đặc trưng", "cornerstone|n|nền tảng cốt lõi",
        "linchpin|n|mấu chốt", "panacea|n|thuốc chữa bách bệnh",
        "caveat|n|điều cần lưu ý", "corollary|n|hệ quả tất yếu",
        "antithesis|n|điều đối lập hoàn toàn", "subtlety|n|sự tinh tế",
        "connoisseur|n|người sành sỏi", "aficionado|n|người đam mê",
        "virtuoso|n|bậc thầy điêu luyện", "prodigy|n|thần đồng",
        "maverick|n|kẻ đi ngược đám đông", "pundit|n|chuyên gia bình luận",
        "demagogue|n|kẻ mị dân", "hegemony|n|quyền bá chủ",
        "orthodoxy|n|chính thống", "dogma|n|giáo điều",
        "ideology|n|hệ tư tưởng", "zeitgeist|n|tinh thần thời đại",
        "renaissance|n|thời kỳ phục hưng", "upheaval|n|biến động lớn",
        "cataclysm|n|thảm hoạ lớn", "attrition|n|sự hao mòn dần",
        "austerity|n|chính sách thắt lưng buộc bụng", "windfall|n|khoản lộc trời cho",
        "largesse|n|sự hào phóng", "parsimony|n|tính hà tiện",
        "prudence|n|sự thận trọng", "candour|n|sự thẳng thắn",
        "duplicity|n|sự hai mặt", "hypocrisy|n|thói đạo đức giả",
        "impunity|n|sự không bị trừng phạt", "reprisal|n|sự trả đũa",
        "retribution|n|sự trừng phạt đích đáng", "absolution|n|sự tha thứ",
        "vindication|n|sự minh oan", "indictment|n|bản cáo trạng",
        "moratorium|n|lệnh tạm hoãn", "embargo|n|lệnh cấm vận",
        "proliferation|n|sự lan rộng nhanh", "confluence|n|sự hội tụ",
        "synergy|n|sự cộng hưởng", "paradigm shift|n|sự thay đổi hệ hình",
        "epistemology|n|nhận thức luận", "ontology|n|bản thể luận",
        "heuristic|n|phương pháp thử sai", "algorithm|n|thuật toán",
        "abstraction|n|sự trừu tượng hoá", "extrapolation|n|phép ngoại suy",
        "inference|n|suy luận", "conjecture|n|phỏng đoán",
        "postulate|n|định đề", "axiom|n|tiên đề",
        "repudiate|v|chối bỏ dứt khoát", "renounce|v|từ bỏ công khai",
        "relinquish|v|nhượng lại", "abdicate|v|thoái vị, thoái thác",
        "capitulate|v|đầu hàng", "acquiesce|v|ngầm chấp thuận",
        "vacillate|v|do dự dao động", "equivocate|v|nói nước đôi",
        "obfuscate|v|làm rối rắm khó hiểu", "elucidate|v|làm sáng tỏ",
        "expound|v|trình bày cặn kẽ", "espouse|v|ủng hộ theo đuổi",
        "corroborate|v|xác nhận thêm", "vindicate|v|minh oan",
        "exonerate|v|giải oan", "incriminate|v|buộc tội",
        "castigate|v|khiển trách gay gắt", "excoriate|v|chỉ trích kịch liệt",
        "vilify|v|bôi nhọ", "extol|v|ca ngợi hết lời",
        "galvanise|v|thúc đẩy mạnh mẽ", "precipitate|v|thúc đẩy xảy ra sớm",
        "engender|v|làm nảy sinh", "supplant|v|thay thế chiếm chỗ",
        "supersede|v|thay thế lỗi thời", "subvert|v|lật đổ ngầm",
        "usurp|v|tiếm quyền", "encroach|v|lấn chiếm",
        "permeate|v|thẩm thấu khắp", "pervade|v|lan toả khắp",
        "delineate|v|phác hoạ rõ ranh giới", "demarcate|v|phân định",
        "extricate|v|gỡ ra khỏi", "assimilate|v|đồng hoá, tiếp thu",
        "ubiquitous|adj|có mặt khắp nơi", "ephemeral|adj|phù du",
        "transient|adj|thoáng qua", "perennial|adj|kéo dài quanh năm",
        "innate|adj|bẩm sinh", "inexorable|adj|không thể lay chuyển",
        "immutable|adj|bất biến", "irrevocable|adj|không thể thu hồi",
        "tenuous|adj|mong manh", "spurious|adj|giả tạo, nguỵ biện",
        "specious|adj|nghe có lý nhưng sai", "fallacious|adj|nguỵ biện",
        "cogent|adj|có sức thuyết phục", "salient|adj|nổi bật đáng chú ý",
        "germane|adj|thích đáng liên quan", "extraneous|adj|không liên quan",
        "superfluous|adj|thừa thãi", "innocuous|adj|vô hại",
        "insidious|adj|ngấm ngầm nguy hại", "pernicious|adj|có hại âm thầm",
        "egregious|adj|tệ hại rõ rành rành", "flagrant|adj|trắng trợn",
        "clandestine|adj|bí mật lén lút", "surreptitious|adj|vụng trộm",
        "ostensible|adj|bề ngoài có vẻ", "putative|adj|được cho là",
        "tacit|adj|ngầm định", "esoteric|adj|khó hiểu với người ngoài",
        "arcane|adj|bí truyền", "byzantine|adj|rối rắm phức tạp",
        "labyrinthine|adj|như mê cung", "fastidious|adj|khó tính cầu kỳ",
        "indefatigable|adj|không biết mệt mỏi", "intransigent|adj|không khoan nhượng",
        "obstinate|adj|ngoan cố", "recalcitrant|adj|ngang bướng chống đối",
        "magnanimous|adj|đại lượng", "altruistic|adj|vị tha",
        "ostensibly|adv|bề ngoài thì", "ostensively|adv|một cách chỉ rõ",
        "categorically|adv|một cách dứt khoát", "unequivocally|adv|không chút mập mờ",
        "inordinately|adv|quá mức", "concomitantly|adv|đồng thời kèm theo",
    ],
}
MARKER = "[seed:wordrain]"


class Command(BaseCommand):
    help = "DEV: nạp từ vựng mẫu 6 cấp CEFR cho path map mini-game."

    def add_arguments(self, parser):
        parser.add_argument("--clear", action="store_true", help="Xoá từ do lệnh này tạo")
        parser.add_argument("--stats", action="store_true", help="Chỉ đếm, không ghi")

    def handle(self, *args, **options):
        if options["stats"]:
            for code in WORDS:
                total = Vocabulary.objects.filter(level_id=code).count()
                mine = Vocabulary.objects.filter(level_id=code, definition_en=MARKER).count()
                stages = (total + 24) // 25
                self.stdout.write(f"{code}: {total} từ ({mine} do seed) → {stages} chặng")
            return

        if options["clear"]:
            deleted, _ = Vocabulary.objects.filter(definition_en=MARKER).delete()
            self.stdout.write(self.style.WARNING(f"Đã xoá {deleted} bản ghi seed."))
            return

        levels = {lv.code: lv for lv in Level.objects.all()}
        missing = [code for code in WORDS if code not in levels]
        if missing:
            self.stderr.write(f"Thiếu Level: {', '.join(missing)}")
            return

        created = updated = 0
        rank = 1
        with transaction.atomic():
            for code, rows in WORDS.items():
                for row in rows:
                    headword, pos, meaning = row.split("|", 2)
                    existing = Vocabulary.objects.filter(headword=headword, pos=pos).first()
                    if existing is None:
                        # Chỉ bản ghi do lệnh này tạo mới mang MARKER, để --clear không
                        # đụng vào từ có sẵn (seed_demo / import_vocab).
                        Vocabulary.objects.create(
                            headword=headword,
                            pos=pos,
                            level=levels[code],
                            meaning_vi=meaning,
                            definition_en=MARKER,
                            frequency_rank=rank,
                        )
                        created += 1
                    else:
                        existing.level = levels[code]
                        existing.frequency_rank = rank
                        if not existing.meaning_vi:
                            existing.meaning_vi = meaning
                        existing.save(
                            update_fields=["level", "frequency_rank", "meaning_vi", "updated_at"]
                        )
                        updated += 1
                    rank += 1

        self.stdout.write(self.style.SUCCESS(f"Tạo mới {created}, cập nhật {updated}."))
        for code in WORDS:
            total = Vocabulary.objects.filter(level_id=code).count()
            self.stdout.write(f"  {code}: {total} từ → {(total + 24) // 25} chặng")
