# Generated by Django 5.1.15 on 2026-09-04 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('skill', models.CharField(choices=[('vocab', 'Từ vựng'), ('grammar', 'Ngữ pháp'), ('listening', 'Nghe')], max_length=10)),
                ('level', models.CharField(choices=[('A1', 'A1 — Mới bắt đầu'), ('A2', 'A2 — Sơ cấp'), ('B1', 'B1 — Trung cấp'), ('B2', 'B2 — Trung cao'), ('C1', 'C1 — Cao cấp'), ('C2', 'C2 — Thành thạo')], max_length=2)),
                ('prompt_en', models.CharField(max_length=512)),
                ('options', models.JSONField()),
                ('answer_index', models.PositiveSmallIntegerField()),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('xp', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveSmallIntegerField(default=0)),
                ('words_reviewed', models.PositiveIntegerField(default=0)),
                ('speaking_count', models.PositiveSmallIntegerField(default=0)),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-date'], name='daily_user_date_idx'), models.Index(fields=['date'], name='daily_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_daily')],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Đang học'), ('completed', 'Hoàn thành')], default='in_progress', max_length=12)),
                ('step_index', models.PositiveSmallIntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-updated_at'], name='lp_user_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_user_lesson')],
            },
        ),
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_word', models.CharField(blank=True, max_length=64)),
                ('custom_meaning', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.vocabulary')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='nb_user_recent_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('vocabulary__isnull', False)), fields=('user', 'vocabulary'), name='uniq_notebook_vocab')],
            },
        ),
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('score_by_skill', models.JSONField(default=dict)),
                ('suggested_level', models.CharField(choices=[('A1', 'A1 — Mới bắt đầu'), ('A2', 'A2 — Sơ cấp'), ('B1', 'B1 — Trung cấp'), ('B2', 'B2 — Trung cao'), ('C1', 'C1 — Cao cấp'), ('C2', 'C2 — Thành thạo')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='placement_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='SRSCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(0, 'Mới'), (1, 'Đang học'), (2, 'Ôn tập'), (3, 'Học lại'), (4, 'Tạm dừng')], default=0)),
                ('due_at', models.DateTimeField()),
                ('stability', models.FloatField(default=0)),
                ('difficulty', models.FloatField(default=0)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to='content.vocabulary')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('state', 4), _negated=True), fields=['user', 'due_at'], name='srs_due_idx'), models.Index(fields=['user', 'state'], name='srs_user_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'vocabulary'), name='uniq_srs_card')],
            },
        ),
        migrations.CreateModel(
            name='SRSReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('state_before', models.SmallIntegerField()),
                ('elapsed_days', models.IntegerField(default=0)),
                ('scheduled_days', models.IntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_logs', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.vocabulary')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'reviewed_at'], name='srslog_user_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_year', models.PositiveSmallIntegerField()),
                ('iso_week', models.PositiveSmallIntegerField()),
                ('xp', models.PositiveIntegerField(default=0)),
                ('days_active', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['iso_year', 'iso_week', '-xp'], name='weekly_rank_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'iso_year', 'iso_week'), name='uniq_weekly')],
            },
        ),
    ]
