# Generated by Django 5.1.15 on 2026-09-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='srscard',
            name='fsrs_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
