# Generated by Django 5.1.15 on 2026-09-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_listeningtopic_listeningitem_and_more"),
        ("learning", "0005_dailyactivity_listening_count_listeningtopicprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingDailyActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reading_daily_activity", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["user", "-date"], name="readact_user_date_idx")],
                "constraints": [models.UniqueConstraint(fields=("user", "date"), name="uniq_reading_daily_activity")],
            },
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("in_progress", "Đang đọc"), ("completed", "Hoàn thành")], default="in_progress", max_length=16)),
                ("answered_count", models.PositiveSmallIntegerField(default=0)),
                ("correct_count", models.PositiveSmallIntegerField(default=0)),
                ("xp_earned", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reading", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reading_progress", to="content.reading")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reading_progress", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "status"], name="readprog_user_status_idx"),
                    models.Index(fields=["user", "-last_read_at"], name="readprog_user_recent_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("user", "reading"), name="uniq_reading_progress")],
            },
        ),
    ]
