# Generated by Django 5.1.15 on 2026-09-14 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_ipa_sound_details'),
        ('learning', '0007_vocabularydeckprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPASoundProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.ipasound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipa_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'sound'), name='uniq_user_ipa_sound')],
            },
        ),
    ]
