# Generated by Django 5.1.15 on 2026-09-15 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_word_root_details'),
        ('learning', '0008_ipa_sound_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRootProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_percent', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('learned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.wordroot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'root'), name='uniq_user_word_root')],
            },
        ),
    ]
