# Generated by Django 5.1.15 on 2026-09-15 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_grammar_exercises_progress'),
        ('learning', '0009_word_root_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_percent', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.grammarpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'grammar_point'), name='uniq_user_grammar_point')],
            },
        ),
    ]
