# Generated by Django 5.1.15 on 2026-09-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_grammar_exercises_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='ai_turns',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
