# Generated by Django 5.1.15 on 2026-09-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_video_practice_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='step_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
