# Generated by Django 5.1.15 on 2026-09-04 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('title_vi', models.CharField(max_length=128)),
                ('description_vi', models.CharField(max_length=255)),
                ('icon_path', models.CharField(blank=True, max_length=255)),
                ('condition', models.JSONField(default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('scope', models.CharField(choices=[('daily', 'Hằng ngày'), ('weekly', 'Hằng tuần'), ('milestone', 'Cột mốc')], max_length=10)),
                ('metric', models.CharField(choices=[('xp', 'XP'), ('words', 'Từ đã ôn'), ('lessons', 'Bài học'), ('days', 'Ngày học'), ('speaking', 'Câu đã nói'), ('exams', 'Đề thi')], max_length=10)),
                ('title_vi', models.CharField(max_length=128)),
                ('description_vi', models.CharField(blank=True, max_length=255)),
                ('target', models.PositiveIntegerField()),
                ('tier', models.PositiveSmallIntegerField(default=1)),
                ('reward_xp', models.PositiveSmallIntegerField(default=0)),
                ('reward_coins', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('title_vi', models.CharField(max_length=64)),
                ('description_vi', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('reflex', 'Phản xạ'), ('memory', 'Ghi nhớ'), ('listening', 'Nghe hiểu')], max_length=10)),
                ('icon_path', models.CharField(blank=True, max_length=255)),
                ('min_level', models.CharField(choices=[('A1', 'A1 — Mới bắt đầu'), ('A2', 'A2 — Sơ cấp'), ('B1', 'B1 — Trung cấp'), ('B2', 'B2 — Trung cao'), ('C1', 'C1 — Cao cấp'), ('C2', 'C2 — Thành thạo')], default='A1', max_length=2)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('title_vi', models.CharField(max_length=128)),
                ('description_vi', models.CharField(max_length=255)),
                ('cost_coins', models.PositiveIntegerField()),
                ('effect', models.JSONField(default=dict)),
                ('icon_path', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.SmallIntegerField(choices=[(1, 'Đồng'), (2, 'Bạc'), (3, 'Vàng'), (4, 'Bạch kim'), (5, 'Kim cương')])),
                ('iso_year', models.PositiveSmallIntegerField()),
                ('iso_week', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['iso_year', 'iso_week', 'tier'], name='league_period_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=48)),
                ('ref_type', models.CharField(blank=True, max_length=32)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('balance_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='coin_user_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1 — Mới bắt đầu'), ('A2', 'A2 — Sơ cấp'), ('B1', 'B1 — Trung cấp'), ('B2', 'B2 — Trung cao'), ('C1', 'C1 — Cao cấp'), ('C2', 'C2 — Thành thạo')], max_length=2)),
                ('score', models.PositiveIntegerField()),
                ('accuracy', models.FloatField(default=0)),
                ('coins_earned', models.PositiveSmallIntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='gamification.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'game', '-score'], name='gs_user_best_idx'), models.Index(fields=['game', '-score'], name='gs_game_rank_idx'), models.Index(fields=['user', '-played_at'], name='gs_user_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_week', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('promoted', models.BooleanField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gamification.leaguegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', '-xp_week'], name='league_rank_idx'), models.Index(fields=['user'], name='league_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='uniq_league_member')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='uniq_user_badge')],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=16)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'period_key'], name='uc_user_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge', 'period_key'), name='uniq_user_challenge')],
            },
        ),
    ]
