# Generated by Django 5.1.15 on 2026-09-10 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1 — Mới bắt đầu'), ('A2', 'A2 — Sơ cấp'), ('B1', 'B1 — Trung cấp'), ('B2', 'B2 — Trung cao'), ('C1', 'C1 — Cao cấp'), ('C2', 'C2 — Thành thạo')], max_length=2)),
                ('stage_index', models.PositiveSmallIntegerField()),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('best_accuracy', models.FloatField(default=0)),
                ('play_count', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='gamification.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'stage_index'],
                'indexes': [models.Index(fields=['user', 'game', 'level'], name='gsp_user_level_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'game', 'level', 'stage_index'), name='uniq_user_game_level_stage')],
            },
        ),
    ]
