# Generated by Django 5.1.15 on 2026-09-11 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_gamestageprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPairsStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('title_vi', models.CharField(max_length=64)),
                ('subtitle_vi', models.CharField(blank=True, max_length=96)),
                ('symbol', models.CharField(blank=True, max_length=4)),
                ('level', models.CharField(choices=[('A1', 'A1 — Mới bắt đầu'), ('A2', 'A2 — Sơ cấp'), ('B1', 'B1 — Trung cấp'), ('B2', 'B2 — Trung cao'), ('C1', 'C1 — Cao cấp'), ('C2', 'C2 — Thành thạo')], default='A1', max_length=2)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchPairsProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó'), ('expert', 'Siêu cấp')], max_length=6)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('best_moves', models.PositiveSmallIntegerField(default=0)),
                ('play_count', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs_progress', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='gamification.matchpairsstage')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'stage'], name='mpp_user_stage_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'stage', 'difficulty'), name='uniq_user_stage_difficulty')],
            },
        ),
        migrations.CreateModel(
            name='MatchPairsWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('english', models.CharField(max_length=48)),
                ('vietnamese', models.CharField(max_length=64)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='gamification.matchpairsstage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('stage', 'english'), name='uniq_stage_english'), models.UniqueConstraint(fields=('stage', 'vietnamese'), name='uniq_stage_vietnamese')],
            },
        ),
    ]
