# Generated by Django 5.1.15 on 2026-09-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_shopitem_options_shopitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='metric',
            field=models.CharField(choices=[('xp', 'XP'), ('words', 'Từ đã ôn'), ('lessons', 'Bài học'), ('days', 'Ngày học'), ('speaking', 'Câu đã nói'), ('exams', 'Đề thi'), ('ai_turns', 'Lượt nói với Long')], max_length=10),
        ),
    ]
