# Generated by Django 5.1.15 on 2026-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_ai_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='integrity',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
