# Generated by Django 5.1.15 on 2026-09-23 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.SlugField(max_length=48, unique=True)),
                ('title_vi', models.CharField(max_length=120)),
                ('description_vi', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(choices=[('rewarded', 'Có thưởng'), ('rewarded_interstitial', 'Xen kẽ có thưởng'), ('interstitial', 'Xen kẽ'), ('native', 'Native')], default='rewarded', max_length=24)),
                ('reward_kind', models.CharField(choices=[('none', 'Không thưởng'), ('coins', 'Xu'), ('hearts', 'Tim')], default='none', max_length=16)),
                ('reward_amount', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=False)),
                ('daily_cap', models.PositiveSmallIntegerField(default=3)),
                ('cooldown_seconds', models.PositiveIntegerField(default=60)),
                ('ad_unit_android', models.CharField(blank=True, max_length=128)),
                ('ad_unit_ios', models.CharField(blank=True, max_length=128)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.SlugField(max_length=48)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác thực'), ('rewarded', 'Đã thưởng'), ('rejected', 'Từ chối'), ('expired', 'Hết hạn')], default='pending', max_length=16)),
                ('reward_kind', models.CharField(default='none', max_length=16)),
                ('reward_amount', models.PositiveSmallIntegerField(default=0)),
                ('granted_amount', models.PositiveSmallIntegerField(default=0)),
                ('local_date', models.DateField()),
                ('ad_network', models.CharField(blank=True, max_length=32)),
                ('ad_unit', models.CharField(blank=True, max_length=128)),
                ('ssv_transaction_id', models.CharField(blank=True, max_length=128)),
                ('signature_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impressions', to='ads.adplacement')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'local_date'], name='ad_user_day_idx'), models.Index(fields=['user', '-created_at'], name='ad_user_recent_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ssv_transaction_id', ''), _negated=True), fields=('ssv_transaction_id',), name='ad_ssv_transaction_unique')],
            },
        ),
    ]
