# Generated by Django 5.1.15 on 2026-09-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplacement',
            name='reward_source',
            field=models.CharField(choices=[('fixed', 'Cố định'), ('last_game_coins', 'Bằng xu ván vừa chơi')], default='fixed', max_length=24),
        ),
    ]
