# Generated by Django 5.1.15 on 2026-09-23 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adplacement_reward_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adimpression',
            name='reward_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['user', 'reward_ref'], name='ad_user_ref_idx'),
        ),
    ]
