# Generated by Django 5.1.15 on 2026-09-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adimpression_reward_ref_adimpression_ad_user_ref_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimpression',
            name='reward_reason',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='reward_reason',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='adplacement',
            name='reward_source',
            field=models.CharField(choices=[('fixed', 'Cố định'), ('last_game_coins', 'Bằng xu ván vừa chơi'), ('last_coin_reward', 'Bằng xu vừa nhận (theo lý do)')], default='fixed', max_length=24),
        ),
    ]
