# Generated by Django 5.1.15 on 2026-09-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='roleplayscenario',
            options={'ordering': ['level', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='goal_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='title_vi',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='topic',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='turn_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='use_notebook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='client_msg_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='ai_role_vi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='coin_reward',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='duration_min',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='goal_hints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='scene',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='tip_vi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='user_role_vi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='roleplayscenario',
            name='xp_reward',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
