# Generated by Django 5.1.15 on 2026-09-25 10:57

from django.db import migrations, models

from apps.common.learning_goals import scenario_goals


def backfill(apps, schema_editor):
    """Điền mục tiêu cho kịch bản đã có theo bối cảnh/chủ đề; seed_scenarios sau này giữ đồng bộ."""
    for sc in apps.get_model("ai", "RoleplayScenario").objects.all():
        sc.learning_goals = scenario_goals(sc.scene, sc.topic)
        sc.save(update_fields=["learning_goals"])


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_tutor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayscenario',
            name='learning_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
