# Generated by Django 5.1.15 on 2026-09-04 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('qtype', models.CharField(choices=[('single', 'Trắc nghiệm'), ('tf', 'Đúng/Sai'), ('fill', 'Điền từ'), ('match', 'Nối')], default='single', max_length=8)),
                ('prompt_en', models.CharField(max_length=512)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer', models.JSONField()),
                ('explanation_vi', models.CharField(blank=True, max_length=512)),
                ('points', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('ielts', 'IELTS'), ('toeic', 'TOEIC'), ('toefl', 'TOEFL')], max_length=8)),
                ('band_group', models.CharField(max_length=16)),
                ('difficulty', models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], max_length=8)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title_vi', models.CharField(max_length=128)),
                ('duration_min', models.PositiveSmallIntegerField(default=60)),
                ('total_questions', models.PositiveSmallIntegerField(default=40)),
                ('pass_score', models.PositiveSmallIntegerField(default=50)),
                ('max_score', models.PositiveSmallIntegerField(default=100)),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['exam_type', 'band_group', 'difficulty'], name='exam_filter_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('band_result', models.CharField(blank=True, max_length=8)),
                ('section_scores', models.JSONField(blank=True, default=dict)),
                ('time_spent_sec', models.PositiveIntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('listening', 'Nghe'), ('reading', 'Đọc')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('instruction_vi', models.CharField(blank=True, max_length=512)),
                ('passage_en', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examsection'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', '-submitted_at'], name='attempt_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'exam'], name='attempt_user_exam_idx'),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_attempt_q'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='uniq_examq_order'),
        ),
    ]
