# Generated by Django 5.1.15 on 2026-09-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='predicted_band',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='skill_tag',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
